import type { FaqItem } from '@/lib/types';

export const faq: FaqItem[] = [
  {
    q: 'What does the JavaScript minifier remove?',
    a: 'The minifier removes single-line comments (// ...), block comments (/* ... */), and all unnecessary whitespace — leading/trailing spaces, blank lines, and extra indentation. It preserves string literals, template literals, and regex patterns exactly as written. Variable names and logic are untouched.',
  },
  {
    q: 'Is the minified output functionally identical to the original?',
    a: 'Yes. The minifier is a whitespace-only compressor — it does not rename variables, reorder expressions, or optimise logic. The output executes identically to the input. The only change is the removal of characters that have no effect on runtime behaviour.',
  },
  {
    q: 'Does it handle template literals and regex patterns correctly?',
    a: 'Yes. Template literals (including ${} interpolations) and regular expressions are scanned character-by-character and emitted verbatim. Whitespace inside strings and patterns is never removed. The minifier uses a heuristic to distinguish regex literals from division operators, which works correctly for standard JavaScript patterns.',
  },
  {
    q: 'How much size reduction can I expect?',
    a: 'Whitespace-only minification typically reduces file size by 20–40% for human-written code. Production minifiers like Terser or esbuild also mangle variable names and eliminate dead code, reaching 50–70% for complex files. For already-minified code, no additional reduction is possible.',
  },
  {
    q: 'Should I minify before or after bundling?',
    a: 'Bundlers like Webpack, Vite, esbuild, and Rollup minify as part of their build pipeline — you rarely need to minify files manually. Use this tool when you have a standalone script (a CDN snippet, a bookmarklet, an inline script tag) that falls outside your main build process.',
  },
  {
    q: 'Is my code sent to a server?',
    a: 'No. All processing runs entirely in your browser using JavaScript. Your code is never uploaded, transmitted, or logged anywhere. The tool works offline and requires no network connection after the page loads.',
  },
  {
    q: 'What about source maps?',
    a: 'This tool does not generate source maps. Source maps link minified code back to the original for debugging — they are generated by production build tools (Webpack, esbuild, Vite) which embed the mapping information in a .map file. For debugging minified production code, use the source maps generated by your build tool.',
  },
  {
    q: 'Can I minify TypeScript with this tool?',
    a: 'No — this tool minifies JavaScript only. TypeScript must be compiled to JavaScript first (using tsc or a bundler). The compiled .js output can then be minified here. If your workflow uses esbuild or Vite, TypeScript compilation and minification happen together in the build step.',
  },
];

export const sidebarInfo = [
  { label: 'Removes',   value: 'Comments · whitespace · blank lines' },
  { label: 'Preserves', value: 'Strings · regex · template literals' },
  { label: 'Privacy',   value: '100% local — no server' },
  { label: 'Input',     value: 'JavaScript (ES5 / ES2015+)' },
];
