export default function RandomTokenGeneratorContent() {
  return (
    <div style={{ maxWidth: 1000, margin: '0 auto', padding: '64px 16px 0' }}>
      <div>

        <section style={{ marginBottom: 48 }}>
          <h2 style={{ fontFamily: 'Outfit, sans-serif', fontWeight: 700, fontSize: 'clamp(18px, 2.5vw, 24px)', color: 'var(--ink)', letterSpacing: '-0.02em', marginBottom: 16 }}>
            What is a cryptographic random token?
          </h2>
          <p style={{ fontSize: 15, lineHeight: 1.75, color: 'var(--ink-2)', marginBottom: 14 }}>
            A cryptographic random token is a fixed-length string generated from a cryptographically secure source of randomness. Unlike tokens produced by standard pseudo-random number generators (like <code style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 13, background: 'var(--border)', padding: '1px 5px', borderRadius: 3 }}>Math.random()</code>), cryptographically secure tokens are computationally unpredictable — even if an attacker knows all previous tokens generated by the system, they cannot predict the next one.
          </p>
          <p style={{ fontSize: 15, lineHeight: 1.75, color: 'var(--ink-2)', marginBottom: 14 }}>
            This tool generates tokens using the <strong style={{ color: 'var(--ink)' }}>Web Crypto API</strong> (<code style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 13, background: 'var(--border)', padding: '1px 5px', borderRadius: 3 }}>crypto.getRandomValues()</code>), which draws from the same entropy pool as your operating system's CSPRNG — the same source used to generate TLS session keys and SSH keys. The randomness quality is identical to what you would get from <code style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 13, background: 'var(--border)', padding: '1px 5px', borderRadius: 3 }}>openssl rand</code> or <code style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 13, background: 'var(--border)', padding: '1px 5px', borderRadius: 3 }}>/dev/urandom</code>.
          </p>
          <p style={{ fontSize: 15, lineHeight: 1.75, color: 'var(--ink-2)' }}>
            Everything runs in your browser — no token is ever sent to a server. All generation happens locally, making this tool safe for generating production secrets.
          </p>
        </section>

        <section style={{ marginBottom: 48 }}>
          <h2 style={{ fontFamily: 'Outfit, sans-serif', fontWeight: 700, fontSize: 'clamp(18px, 2.5vw, 24px)', color: 'var(--ink)', letterSpacing: '-0.02em', marginBottom: 16 }}>
            Token formats explained
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {[
              {
                fmt: 'Hex',
                chars: '0–9, a–f',
                efficiency: '50% — 1 byte = 2 chars',
                example: 'a3f2b1e4c9d87654321a3f2b1e4c9d876',
                use: 'Universal. Works in any context — URLs, headers, JSON, logs. The most readable format. Preferred for hashes, session IDs, and any context where the token needs to be inspected.',
              },
              {
                fmt: 'Base64',
                chars: 'A–Z, a–z, 0–9, +, /',
                efficiency: '75% — 3 bytes = 4 chars',
                example: 'o/K1xJy8dlU=',
                use: 'More compact than hex. The + and / characters require URL-encoding in query strings, so Base64 is best for HTTP headers, email content, and binary data transmission (like email attachments or data URIs).',
              },
              {
                fmt: 'Base64url',
                chars: 'A–Z, a–z, 0–9, -, _',
                efficiency: '75% — same as Base64, no padding',
                example: 'o_K1xJy8dlU',
                use: 'URL-safe Base64. No padding characters. Used in JWTs, OAuth tokens, and anywhere the token will appear in a URL path or query string. The format used by crypto.randomUUID() for UUID v4.',
              },
              {
                fmt: 'Alphanumeric',
                chars: 'A–Z, a–z, 0–9',
                efficiency: '~60% — slightly less than Base64',
                example: 'Xk9mL2vQ8nDp4rTy',
                use: 'Universally safe — no special characters to escape in any context. Slightly lower entropy per character than hex or Base64. Best for tokens that will appear in user-facing contexts, SMS messages, or systems with restricted character sets.',
              },
            ].map(({ fmt, chars, efficiency, example, use }) => (
              <div key={fmt} style={{ padding: '16px', background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 'var(--r-l)' }}>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, alignItems: 'baseline', marginBottom: 8 }}>
                  <span style={{ fontSize: 15, fontWeight: 700, color: 'var(--ink)', fontFamily: 'JetBrains Mono, monospace' }}>{fmt}</span>
                  <span style={{ fontSize: 11, color: 'var(--ink-4)' }}>chars: {chars}</span>
                  <span style={{ fontSize: 11, color: 'var(--ink-4)' }}>efficiency: {efficiency}</span>
                </div>
                <code style={{ display: 'block', fontSize: 12, fontFamily: 'JetBrains Mono, monospace', color: 'var(--green)', background: 'var(--green-lt)', padding: '4px 8px', borderRadius: 4, marginBottom: 8, wordBreak: 'break-all' }}>{example}</code>
                <p style={{ fontSize: 13, color: 'var(--ink-2)', lineHeight: 1.65, margin: 0 }}>{use}</p>
              </div>
            ))}
          </div>
        </section>

        <section style={{ marginBottom: 48 }}>
          <h2 style={{ fontFamily: 'Outfit, sans-serif', fontWeight: 700, fontSize: 'clamp(18px, 2.5vw, 24px)', color: 'var(--ink)', letterSpacing: '-0.02em', marginBottom: 16 }}>
            How many bytes do I need?
          </h2>
          <p style={{ fontSize: 15, lineHeight: 1.75, color: 'var(--ink-2)', marginBottom: 16 }}>
            The required length depends on the security requirements of the token's use case. More bytes = more entropy = harder to guess or brute-force:
          </p>
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}>
              <thead>
                <tr style={{ background: 'var(--ink)', color: '#fff' }}>
                  {['Bytes', 'Entropy', 'Use case', 'Length in hex'].map(h => (
                    <th key={h} style={{ padding: '10px 14px', textAlign: 'left', fontWeight: 600, fontFamily: 'Outfit, sans-serif', whiteSpace: 'nowrap' }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {[
                  ['16', '128 bits', 'CSRF tokens, short-lived codes',    '32 hex chars'],
                  ['24', '192 bits', 'Session tokens, email verify links', '48 hex chars'],
                  ['32', '256 bits', 'API secrets, JWT signing keys',       '64 hex chars'],
                  ['48', '384 bits', 'Long-lived API keys, root secrets',  '96 hex chars'],
                  ['64', '512 bits', 'Master secrets, key derivation',    '128 hex chars'],
                ].map(([bytes, ent, use, hex], i) => (
                  <tr key={bytes} style={{ background: i % 2 === 0 ? 'var(--white)' : 'var(--page-bg)', borderBottom: '1px solid var(--border)' }}>
                    <td style={{ padding: '10px 14px', fontFamily: 'JetBrains Mono, monospace', fontWeight: 700, color: 'var(--green)' }}>{bytes}</td>
                    <td style={{ padding: '10px 14px', fontFamily: 'JetBrains Mono, monospace', color: 'var(--ink-2)' }}>{ent}</td>
                    <td style={{ padding: '10px 14px', color: 'var(--ink-2)' }}>{use}</td>
                    <td style={{ padding: '10px 14px', fontFamily: 'JetBrains Mono, monospace', fontSize: 12, color: 'var(--ink-3)' }}>{hex}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section style={{ marginBottom: 48 }}>
          <h2 style={{ fontFamily: 'Outfit, sans-serif', fontWeight: 700, fontSize: 'clamp(18px, 2.5vw, 24px)', color: 'var(--ink)', letterSpacing: '-0.02em', marginBottom: 16 }}>
            Generating tokens in code
          </h2>
          <p style={{ fontSize: 15, lineHeight: 1.75, color: 'var(--ink-2)', marginBottom: 16 }}>
            Always use your language's cryptographic random module. Never use general-purpose random functions for security-sensitive tokens:
          </p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {[
              { lang: 'JavaScript / Node.js', code: "crypto.randomBytes(32).toString('hex')  // Node.js\ncrypto.getRandomValues(new Uint8Array(32))  // Browser" },
              { lang: 'Python',               code: "import secrets\nsecrets.token_hex(32)        # hex\nsecrets.token_urlsafe(32)    # base64url" },
              { lang: 'Go',                   code: 'import "crypto/rand"\nimport "encoding/hex"\nbytes := make([]byte, 32)\nrand.Read(bytes)\nhex.EncodeToString(bytes)' },
              { lang: 'PHP',                  code: 'bin2hex(random_bytes(32))  // hex\nbase64_encode(random_bytes(32))  // base64' },
              { lang: 'Ruby',                 code: 'require "securerandom"\nSecureRandom.hex(32)\nSecureRandom.base64(32)\nSecureRandom.urlsafe_base64(32)' },
            ].map(({ lang, code }) => (
              <div key={lang} style={{ padding: '12px 16px', background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 'var(--r-l)' }}>
                <div style={{ fontSize: 12, fontWeight: 700, color: 'var(--ink-3)', marginBottom: 6, textTransform: 'uppercase', letterSpacing: '0.06em' }}>{lang}</div>
                <pre style={{ margin: 0, fontSize: 12, fontFamily: 'JetBrains Mono, monospace', color: 'var(--ink)', background: 'var(--page-bg)', padding: '10px 12px', borderRadius: 'var(--r-s)', overflowX: 'auto', lineHeight: 1.7 }}>{code}</pre>
              </div>
            ))}
          </div>
        </section>

        <section style={{ marginBottom: 48 }}>
          <h2 style={{ fontFamily: 'Outfit, sans-serif', fontWeight: 700, fontSize: 'clamp(18px, 2.5vw, 24px)', color: 'var(--ink)', letterSpacing: '-0.02em', marginBottom: 16 }}>
            Token security and best practices
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {[
              { title: 'Never use Math.random() for security',   body: 'Math.random() is a pseudo-random number generator seeded with a predictable value. It is not suitable for security tokens — an attacker who observes several outputs can reconstruct the internal state and predict future values. Always use crypto.getRandomValues() or your language\'s equivalent.' },
              { title: 'Store secrets in environment variables', body: 'Never hardcode tokens or secrets in source code. Use .env files locally, CI/CD secret variables for pipelines, and dedicated secrets managers (AWS Secrets Manager, Vault, Doppler) in production. Add .env to .gitignore before your first commit and keep it there.' },
              { title: 'Rotate tokens on security events',       body: 'Immediately invalidate and regenerate tokens when: a team member with access leaves, you suspect a token was exposed in logs or error messages, or a dependency vulnerability is disclosed. For API keys, maintain a grace period where both old and new tokens work to avoid service disruption.' },
              { title: 'Use token hashing for database storage', body: 'Store SHA-256(token) in the database, never the plaintext token. Show the full token to the user exactly once at creation. On subsequent requests, hash the received token and compare. This prevents database breaches from yielding usable credentials. See <a href="/tools/hash-generator">Hash Generator</a> for SHA-256 hashing.' },
              { title: 'Set appropriate token expiry',           body: 'Short-lived tokens for interactive sessions (15–60 minutes), medium-lived for API access (24 hours for developer APIs), long-lived for server-to-server keys that are rotated manually. Combine with refresh token patterns for interactive apps.' },
            ].map(({ title, body }, i) => (
              <div key={title} style={{ padding: '14px 16px', background: i % 2 === 0 ? 'var(--white)' : 'var(--page-bg)', border: '1px solid var(--border)', borderRadius: 'var(--r-l)' }}>
                <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--ink)', marginBottom: 6 }}>{title}</div>
                <p style={{ fontSize: 14, lineHeight: 1.65, color: 'var(--ink-2)', margin: 0 }} dangerouslySetInnerHTML={{ __html: body }} />
              </div>
            ))}
          </div>
          <p style={{ fontSize: 15, lineHeight: 1.75, color: 'var(--ink-2)', marginTop: 16 }}>
            For generating structured API keys with custom prefixes, use the <a href="/tools/api-key-generator" style={{ color: 'var(--green)', textDecoration: 'underline' }}>API Key Generator</a>. For HMAC signing of tokens and webhooks, use the <a href="/tools/hmac-generator" style={{ color: 'var(--green)', textDecoration: 'underline' }}>HMAC Generator</a>.
          </p>
        </section>

      </div>
    </div>
  );
}
