import type { ToolMeta } from './types';
import { variants as passwordGeneratorVariants } from '@/tools/password-generator/variants';

export const TOOLS: ToolMeta[] = [
  {
    slug:           'password-generator',
    name:           'Password Generator',
    tagline:        'Strong random passwords with custom settings',
    description:    'Create strong, cryptographically random passwords. No signup, nothing stored.',
    seoTitle:       'Free Password Generator — Strong & Secure Random Passwords | ToolKit',
    seoH1:          'Free Password Generator Online',
    seoDescription: 'Generate strong, random passwords instantly. Customize length, uppercase, symbols & more. 100% browser-based — your passwords never leave your device. Free, no signup.',
    category:       'Security',
    keywords:       ['password generator', 'strong password generator', 'random password generator', 'secure password generator', 'online password generator'],
    live:           true,
    featured:       true,
    variants:       passwordGeneratorVariants
  },
  {
    slug:           'word-counter',
    name:           'Word Counter',
    tagline:        'Words, characters, sentences & reading time',
    description:    'Count words, characters, sentences, paragraphs and reading time instantly.',
    seoTitle:       'Free Word Counter Online — Count Words, Characters & Reading Time | ToolKit',
    seoH1:          'Free Word Counter Online',
    seoDescription: 'Count words, characters, sentences, paragraphs and reading time instantly. Includes keyword density and speaking time. Free online tool — no signup required.',
    category:       'Text & Writing',
    keywords:       ['word counter', 'word counter online', 'character counter', 'word count tool', 'reading time calculator', 'online word counter free'],
    live:           true,
  },
  {
    slug:           'lorem-ipsum',
    name:           'Lorem Ipsum Generator',
    tagline:        'Placeholder text for mockups & design',
    description:    'Generate Lorem Ipsum placeholder text by words, sentences, or paragraphs.',
    seoTitle:       'Free Lorem Ipsum Generator — Placeholder Text for Mockups | ToolKit',
    seoH1:          'Free Lorem Ipsum Generator Online',
    seoDescription: 'Generate Lorem Ipsum placeholder text instantly. Choose words, sentences or paragraphs. Classic and random variants. Free online tool for designers and developers.',
    category:       'Text & Writing',
    keywords:       ['lorem ipsum generator', 'lorem ipsum', 'placeholder text generator', 'dummy text generator', 'lorem ipsum online'],
    live:           true,
  },
  {
    slug:           'uuid-generator',
    name:           'UUID Generator',
    tagline:        'Generate v4 UUIDs instantly',
    description:    'Generate cryptographically random UUID v4 identifiers in one click.',
    seoTitle:       'Free UUID Generator Online — Generate v4 UUIDs Instantly | ToolKit',
    seoH1:          'Free UUID Generator Online',
    seoDescription: 'Generate cryptographically random UUID v4 identifiers instantly. Generate 1–50 UUIDs at once, copy all with one click. Free, browser-based, no signup.',
    category:       'Developer Tools',
    keywords:       ['uuid generator', 'uuid generator online', 'unique id generator', 'guid generator', 'random uuid', 'uuid v4 generator'],
    live:           true,
  },
  {
    slug:           'base64',
    name:           'Base64 Encoder / Decoder',
    tagline:        'Encode or decode Base64 strings instantly',
    description:    'Encode text to Base64 or decode Base64 strings back to plain text.',
    seoTitle:       'Free Base64 Encoder & Decoder Online — Encode & Decode Instantly | ToolKit',
    seoH1:          'Free Base64 Encoder & Decoder Online',
    seoDescription: 'Encode text to Base64 or decode Base64 strings back to plain text instantly. Supports UTF-8. Free online Base64 converter — no signup, works in your browser.',
    category:       'Developer Tools',
    keywords:       ['base64 encoder', 'base64 decoder', 'base64 encode', 'base64 decode', 'base64 converter online', 'encode to base64'],
    live:           true,
  },
  {
    slug:           'csv-to-json',
    name:           'CSV to JSON',
    tagline:        'Convert CSV data to JSON instantly',
    description:    'Convert CSV files to JSON arrays. Supports custom delimiters, header rows, type coercion, and one-click download.',
    seoTitle:       'Free CSV to JSON Converter Online — Convert CSV to JSON Instantly | ToolKit',
    seoH1:          'Free CSV to JSON Converter Online',
    seoDescription: 'Convert CSV to JSON instantly in your browser. Supports comma, semicolon, tab and pipe delimiters. Auto-detects numbers and booleans. Download the result as a .json file. Free, no signup, no data sent to any server.',
    category:       'Developer Tools',
    keywords:       ['csv to json', 'csv to json converter', 'convert csv to json', 'csv to json online', 'csv json converter', 'parse csv online', 'csv converter'],
    live:           true,
  },
  {
    slug:           'json-formatter',
    name:           'JSON Formatter',
    tagline:        'Prettify, minify & validate JSON',
    description:    'Format, beautify, minify and validate JSON data online.',
    seoTitle:       'Free JSON Formatter Online — Prettify, Minify & Validate JSON | ToolKit',
    seoH1:          'Free JSON Formatter & Validator Online',
    seoDescription: 'Format, beautify, minify and validate JSON data instantly. Choose 2 or 4-space indentation. Highlights syntax errors. Free online JSON formatter — no signup.',
    category:       'Developer Tools',
    keywords:       ['json formatter', 'json formatter online', 'json beautifier', 'json validator', 'json prettify', 'format json online', 'json minifier'],
    live:           true,
  },
  {
    slug:           'url-encoder',
    name:           'URL Encoder / Decoder',
    tagline:        'Encode and decode URLs instantly',
    description:    'Encode special characters in URLs or decode percent-encoded strings.',
    seoTitle:       'Free URL Encoder & Decoder Online — Percent Encode / Decode | ToolKit',
    seoH1:          'Free URL Encoder & Decoder Online',
    seoDescription: 'Encode special characters in URLs or decode percent-encoded strings instantly. Swap encode/decode with one click. Free online URL converter — no signup required.',
    category:       'Developer Tools',
    keywords:       ['url encoder', 'url decoder', 'url encode online', 'url decode online', 'percent encoding', 'urlencode', 'url encoding tool'],
    live:           true,
  },
  {
    slug:           'hash-generator',
    name:           'Hash Generator',
    tagline:        'SHA-1, SHA-256, SHA-384, SHA-512 hashes',
    description:    'Generate SHA-1, SHA-256, SHA-384 and SHA-512 hashes from any text.',
    seoTitle:       'Free Hash Generator Online — SHA-256, SHA-512, SHA-1 | ToolKit',
    seoH1:          'Free Hash Generator Online',
    seoDescription: 'Generate SHA-1, SHA-256, SHA-384 and SHA-512 hashes from any text instantly. All hashing runs in your browser via Web Crypto API. Free, no signup, no data stored.',
    category:       'Security',
    keywords:       ['hash generator', 'sha256 generator', 'sha-256 online', 'sha512 generator', 'sha1 hash online', 'text hash generator', 'hash string online'],
    live:           true,
  },
  {
    slug:           'case-converter',
    name:           'Case Converter',
    tagline:        'UPPER, lower, Title, camelCase, snake_case & more',
    description:    'Convert text between uppercase, lowercase, camelCase, snake_case, kebab-case and more.',
    seoTitle:       'Free Case Converter Online — camelCase, snake_case, Title Case & More | ToolKit',
    seoH1:          'Free Case Converter Online',
    seoDescription: 'Convert text to uppercase, lowercase, Title Case, camelCase, PascalCase, snake_case, kebab-case and CONSTANT_CASE instantly. Free online text case converter — no signup.',
    category:       'Text & Writing',
    keywords:       ['case converter', 'text case converter', 'camelcase converter', 'snake case converter', 'uppercase lowercase converter', 'title case converter', 'convert to camelcase'],
    live:           true,
  },
  {
    slug:           'markdown-editor',
    name:           'Markdown Editor',
    tagline:        'Write and preview Markdown live',
    description:    'Write Markdown with live HTML preview. Copy output as HTML.',
    seoTitle:       'Free Online Markdown Editor — Live Preview & HTML Export | ToolKit',
    seoH1:          'Free Online Markdown Editor with Live Preview',
    seoDescription: 'Write Markdown with instant live preview. Supports headings, bold, italic, code blocks, lists, links and tables. Export as HTML. Free online Markdown editor — no signup.',
    category:       'Text & Writing',
    keywords:       ['markdown editor', 'markdown editor online', 'markdown preview', 'online markdown editor', 'markdown to html', 'live markdown editor'],
    live:           true,
  },
  {
    slug:           'color-palette',
    name:           'Color Palette Generator',
    tagline:        'Generate harmonious color palettes',
    description:    'Generate harmonious color palettes with 7 harmony modes. Copy HEX, RGB, HSL or CSS.',
    seoTitle:       'Free Color Palette Generator — Analogous, Complementary & More | ToolKit',
    seoH1:          'Free Color Palette Generator Online',
    seoDescription: 'Generate beautiful color palettes instantly. Choose analogous, complementary, triadic, tetradic, monochromatic and more. Copy HEX, RGB, HSL or CSS variables. Free, no signup.',
    category:       'Design',
    keywords:       ['color palette generator', 'color palette generator online', 'color scheme generator', 'color picker online', 'complementary color generator', 'color harmony tool'],
    live:           true,
  },
  {
    slug:           'username-generator',
    name:           'Username Generator',
    tagline:        'Creative usernames for social media & gaming',
    description:    'Generate unique usernames for social media, gaming and professional accounts.',
    seoTitle:       'Free Username Generator — Creative Usernames for Social Media & Gaming | ToolKit',
    seoH1:          'Free Username Generator Online',
    seoDescription: 'Generate creative, unique usernames for social media, gaming, Discord, Twitch and more. Choose fun, professional, gamer or minimal styles. Free online username generator.',
    category:       'Design',
    keywords:       ['username generator', 'username generator online', 'random username generator', 'nickname generator', 'gamertag generator', 'discord username generator'],
    live:           true,
  },

  /* ── Coming soon — Security ─────────────────────────── */
  {
    slug:           'bcrypt-generator',
    name:           'Bcrypt Generator',
    tagline:        'Hash and verify passwords with bcrypt',
    description:    'Generate bcrypt hashes from passwords and verify them. Adjustable cost factor.',
    seoTitle:       'Free Bcrypt Generator & Verifier Online | ToolKit',
    seoH1:          'Free Bcrypt Password Hash Generator',
    seoDescription: 'Generate and verify bcrypt password hashes online. Choose cost factor 4–12. Free browser-based bcrypt tool — no data sent to any server.',
    category:       'Security',
    keywords:       ['bcrypt generator', 'bcrypt hash online', 'bcrypt password', 'bcrypt verifier'],
    live:           false,
  },
  {
    slug:           'jwt-decoder',
    name:           'JWT Decoder',
    tagline:        'Decode and inspect JWT tokens',
    description:    'Decode JWT tokens and inspect header, payload and signature. No verification needed.',
    seoTitle:       'Free JWT Decoder Online — Decode & Inspect JSON Web Tokens | ToolKit',
    seoH1:          'Free JWT Decoder Online',
    seoDescription: 'Decode and inspect JWT tokens instantly. View header, payload and signature. Verify expiration. Free online JWT decoder — no data sent to servers.',
    category:       'Security',
    keywords:       ['jwt decoder', 'jwt decoder online', 'decode jwt token', 'json web token decoder', 'jwt inspector'],
    live:           true,
  },
  {
    slug:           'password-strength-checker',
    name:           'Password Strength Checker',
    tagline:        'Analyse password strength and entropy',
    description:    'Check how strong a password is. Get entropy score, crack-time estimate and improvement tips.',
    seoTitle:       'Free Password Strength Checker Online — Entropy & Crack Time | ToolKit',
    seoH1:          'Free Password Strength Checker Online',
    seoDescription: 'Analyse password strength instantly. See entropy bits, estimated crack time and specific improvement tips. 100% browser-based — your password never leaves your device.',
    category:       'Security',
    keywords:       ['password strength checker', 'password strength meter', 'how strong is my password', 'password entropy calculator'],
    live:           true,
  },
  {
    slug:           'encryption-tool',
    name:           'Text Encryption Tool',
    tagline:        'AES-256 encrypt and decrypt text in browser',
    description:    'Encrypt and decrypt text with AES-256-GCM. Passphrase-based, fully browser-side.',
    seoTitle:       'Free AES Text Encryption Tool Online — Encrypt & Decrypt | ToolKit',
    seoH1:          'Free AES-256 Text Encryption Tool',
    seoDescription: 'Encrypt and decrypt text with AES-256-GCM using a passphrase. All processing runs in your browser — nothing is sent to any server. Free, no signup.',
    category:       'Security',
    keywords:       ['text encryption tool', 'aes encrypt online', 'encrypt text online', 'decrypt text online', 'aes-256 encryption'],
    live:           false,
  },
  {
    slug:           'hmac-generator',
    name:           'HMAC Generator',
    tagline:        'Generate HMAC signatures with SHA-256 or SHA-512',
    description:    'Generate HMAC-SHA256 and HMAC-SHA512 message authentication codes from any text and secret key.',
    seoTitle:       'Free HMAC Generator Online — HMAC-SHA256, SHA-512 | ToolKit',
    seoH1:          'Free HMAC Generator Online',
    seoDescription: 'Generate HMAC-SHA256 and HMAC-SHA512 signatures from a message and secret key. Fully browser-based via Web Crypto API. Free, no data stored.',
    category:       'Security',
    keywords:       ['hmac generator', 'hmac sha256 online', 'hmac sha512', 'message authentication code', 'hmac calculator'],
    live:           true,
  },
  {
    slug:           'totp-generator',
    name:           'TOTP Code Generator',
    tagline:        'Generate time-based one-time passwords',
    description:    'Generate TOTP codes compatible with Google Authenticator and Authy from any TOTP secret key.',
    seoTitle:       'Free TOTP Generator Online — Time-Based OTP Codes | ToolKit',
    seoH1:          'Free TOTP Code Generator Online',
    seoDescription: 'Generate TOTP one-time codes from any TOTP secret key. Compatible with Google Authenticator, Authy, and RFC 6238. Free, browser-based, no signup.',
    category:       'Security',
    keywords:       ['totp generator', 'otp generator online', 'google authenticator code generator', 'totp code', 'time-based otp'],
    live:           false,
  },
  {
    slug:           'random-token-generator',
    name:           'Random Token Generator',
    tagline:        'Cryptographically secure random tokens and secrets',
    description:    'Generate cryptographically secure random tokens, secrets and keys in hex, base64 or alphanumeric format.',
    seoTitle:       'Free Random Token Generator Online — Secure Secrets & Keys | ToolKit',
    seoH1:          'Free Cryptographic Token Generator Online',
    seoDescription: 'Generate cryptographically secure random tokens, API secrets and keys. Choose length and format: hex, base64 or alphanumeric. Uses Web Crypto API. Free, no signup.',
    category:       'Security',
    keywords:       ['random token generator', 'secure token generator', 'crypto random generator', 'secret key generator', 'random secret generator'],
    live:           true,
  },
  {
    slug:           'api-key-generator',
    name:           'API Key Generator',
    tagline:        'Generate formatted API keys instantly',
    description:    'Generate API keys in various formats: UUID-style, hex, base64, prefixed. Cryptographically random.',
    seoTitle:       'Free API Key Generator Online — UUID, Hex & Prefixed Keys | ToolKit',
    seoH1:          'Free API Key Generator Online',
    seoDescription: 'Generate API keys instantly in multiple formats — UUID-style, hex, base64 or custom prefix. All keys are cryptographically random. Free, browser-based, no signup.',
    category:       'Security',
    keywords:       ['api key generator', 'generate api key', 'random api key', 'api key creator online'],
    live:           true,
  },
  {
    slug:           'ssl-certificate-decoder',
    name:           'SSL Certificate Decoder',
    tagline:        'Decode and inspect PEM SSL certificates',
    description:    'Paste a PEM-encoded SSL certificate and inspect its subject, issuer, validity dates and SANs.',
    seoTitle:       'Free SSL Certificate Decoder Online — Inspect PEM Certificates | ToolKit',
    seoH1:          'Free SSL Certificate Decoder Online',
    seoDescription: 'Decode and inspect PEM-encoded SSL/TLS certificates. View subject, issuer, validity dates, SAN entries and fingerprints. Free, browser-based, no signup.',
    category:       'Security',
    keywords:       ['ssl certificate decoder', 'pem decoder online', 'ssl certificate viewer', 'x509 decoder', 'certificate inspector'],
    live:           false,
  },
  {
    slug:           'qr-code-generator',
    name:           'QR Code Generator',
    tagline:        'Generate QR codes for URLs and text',
    description:    'Generate QR codes for any URL, text, WiFi, email or phone. Download as PNG or SVG. No watermark, no signup.',
    seoTitle:       'Free QR Code Generator — Create QR Codes Instantly, No Signup | ToolKit',
    seoH1:          'Free QR Code Generator Online',
    seoDescription: 'Generate QR codes for URLs, WiFi, email, phone and more. Download as PNG or SVG. Customize colors and size. 100% free, no watermark, no signup — works in your browser.',
    category:       'Security',
    keywords:       ['qr code generator', 'qr code generator online', 'free qr code generator', 'create qr code', 'qr generator', 'qr code maker', 'qr code creator', 'wifi qr code generator'],
    live:           true,
  },

  /* ── Coming soon — Text & Writing ───────────────────── */
  {
    slug:           'text-to-slug',
    name:           'Text to Slug Converter',
    tagline:        'Convert text to URL-friendly slugs',
    description:    'Convert any text to clean URL slugs. Handles spaces, accents, special characters and case.',
    seoTitle:       'Free Text to Slug Converter Online — URL-Friendly Slugs | ToolKit',
    seoH1:          'Free Text to Slug Converter Online',
    seoDescription: 'Convert text to URL-friendly slugs instantly. Handles accented characters, spaces, symbols and mixed case. Free online slug generator — no signup.',
    category:       'Text & Writing',
    keywords:       ['text to slug', 'slug generator', 'url slug converter', 'slugify text online', 'permalink generator'],
    live:           true,
  },
  {
    slug:           'duplicate-line-remover',
    name:           'Duplicate Line Remover',
    tagline:        'Remove duplicate lines from any text',
    description:    'Remove duplicate lines from text. Case-sensitive or insensitive, with sorting options.',
    seoTitle:       'Free Duplicate Line Remover Online — Remove Repeated Lines | ToolKit',
    seoH1:          'Free Duplicate Line Remover Online',
    seoDescription: 'Remove duplicate lines from any text instantly. Choose case-sensitive or insensitive matching, sort results, and keep or discard blank lines. Free, no signup.',
    category:       'Text & Writing',
    keywords:       ['duplicate line remover', 'remove duplicate lines online', 'remove duplicates text', 'unique lines extractor'],
    live:           true,
  },
  {
    slug:           'sort-lines',
    name:           'Sort Lines',
    tagline:        'Sort text lines alphabetically or by length',
    description:    'Sort lines of text alphabetically, by length, numerically, or in reverse order.',
    seoTitle:       'Free Sort Lines Tool Online — Alphabetical, Reverse & More | ToolKit',
    seoH1:          'Free Sort Lines Tool Online',
    seoDescription: 'Sort lines of text alphabetically, by length, numerically or in reverse order. Remove duplicates while sorting. Free online line sorter — no signup.',
    category:       'Text & Writing',
    keywords:       ['sort lines online', 'sort text lines alphabetically', 'line sorter', 'sort list online', 'alphabetical sorter'],
    live:           true,
  },
  {
    slug:           'reverse-text',
    name:           'Reverse Text',
    tagline:        'Reverse text, words or lines instantly',
    description:    'Reverse any text character by character, word by word, or line by line.',
    seoTitle:       'Free Reverse Text Generator Online — Flip Text, Words & Lines | ToolKit',
    seoH1:          'Free Reverse Text Generator Online',
    seoDescription: 'Reverse text instantly — flip characters, words or entire lines. Useful for mirror text, fun messages and development testing. Free, no signup.',
    category:       'Text & Writing',
    keywords:       ['reverse text', 'reverse text generator', 'flip text online', 'backwards text generator', 'mirror text'],
    live:           true,
  },
  {
    slug:           'text-repeater',
    name:           'Text Repeater',
    tagline:        'Repeat any text N times with a separator',
    description:    'Repeat any text or character a specified number of times. Choose separator.',
    seoTitle:       'Free Text Repeater Online — Repeat Text N Times | ToolKit',
    seoH1:          'Free Text Repeater Online',
    seoDescription: 'Repeat any text or string a custom number of times with an optional separator. Useful for generating test data and placeholder content. Free, no signup.',
    category:       'Text & Writing',
    keywords:       ['text repeater', 'repeat text online', 'duplicate text generator', 'string repeater'],
    live:           false,
  },
  {
    slug:           'find-and-replace',
    name:           'Find and Replace',
    tagline:        'Find and replace text with regex support',
    description:    'Find and replace text with plain string or regex. Supports case sensitivity and global replace.',
    seoTitle:       'Free Find and Replace Tool Online — Regex Support | ToolKit',
    seoH1:          'Free Find and Replace Text Tool Online',
    seoDescription: 'Find and replace text online with plain text or regex patterns. Supports case-sensitive matching, global replace and regex flags. Free, no signup.',
    category:       'Text & Writing',
    keywords:       ['find and replace online', 'text find replace tool', 'regex find replace', 'bulk text replace online'],
    live:           true,
  },
  {
    slug:           'remove-whitespace',
    name:           'Whitespace Remover',
    tagline:        'Strip extra spaces, tabs and blank lines',
    description:    'Remove extra whitespace from text: leading/trailing spaces, double spaces, blank lines.',
    seoTitle:       'Free Whitespace Remover Online — Strip Extra Spaces & Tabs | ToolKit',
    seoH1:          'Free Whitespace Remover Online',
    seoDescription: 'Remove extra whitespace from text instantly — strip leading/trailing spaces, collapse double spaces, remove blank lines and tabs. Free online tool, no signup.',
    category:       'Text & Writing',
    keywords:       ['whitespace remover', 'remove extra spaces online', 'trim whitespace tool', 'strip spaces from text', 'clean text whitespace'],
    live:           false,
  },
  {
    slug:           'text-to-morse',
    name:           'Morse Code Translator',
    tagline:        'Convert text to Morse code and back',
    description:    'Translate text to Morse code or decode Morse code back to plain text.',
    seoTitle:       'Free Morse Code Translator Online — Text to Morse & Back | ToolKit',
    seoH1:          'Free Morse Code Translator Online',
    seoDescription: 'Convert text to Morse code or translate Morse code back to plain text instantly. Supports international Morse code standard. Free, no signup.',
    category:       'Text & Writing',
    keywords:       ['morse code translator', 'text to morse code', 'morse code converter online', 'decode morse code', 'morse encoder decoder'],
    live:           false,
  },
  {
    slug:           'nato-alphabet',
    name:           'NATO Alphabet Converter',
    tagline:        'Convert text to NATO phonetic alphabet',
    description:    'Spell out any text using the NATO phonetic alphabet (Alpha, Bravo, Charlie…).',
    seoTitle:       'Free NATO Phonetic Alphabet Converter Online | ToolKit',
    seoH1:          'Free NATO Phonetic Alphabet Converter',
    seoDescription: 'Convert any text to NATO phonetic alphabet spelling instantly. Alpha, Bravo, Charlie — great for phone communication and clarity. Free, no signup.',
    category:       'Text & Writing',
    keywords:       ['nato alphabet converter', 'phonetic alphabet online', 'nato phonetic alphabet', 'spell out text nato'],
    live:           false,
  },
  {
    slug:           'rot13-encoder',
    name:           'ROT13 Encoder / Decoder',
    tagline:        'Encode and decode text with ROT13 cipher',
    description:    'Encode or decode any text with the ROT13 substitution cipher. Same tool encodes and decodes.',
    seoTitle:       'Free ROT13 Encoder & Decoder Online — ROT13 Cipher Tool | ToolKit',
    seoH1:          'Free ROT13 Encoder & Decoder Online',
    seoDescription: 'Encode and decode text with the ROT13 cipher instantly. The same tool encodes and decodes — just paste your text and see the result. Free, no signup.',
    category:       'Text & Writing',
    keywords:       ['rot13 encoder', 'rot13 decoder', 'rot13 cipher online', 'rot13 converter', 'caesar cipher online'],
    live:           false,
  },
  {
    slug:           'text-to-binary',
    name:           'Text to Binary Converter',
    tagline:        'Convert text to binary and binary to text',
    description:    'Convert plain text to binary (0s and 1s) or decode binary back to readable text.',
    seoTitle:       'Free Text to Binary Converter Online — Encode & Decode Binary | ToolKit',
    seoH1:          'Free Text to Binary Converter Online',
    seoDescription: 'Convert text to binary representation (0s and 1s) or decode binary back to readable text. Also supports hex and octal output. Free, no signup.',
    category:       'Text & Writing',
    keywords:       ['text to binary', 'binary to text converter', 'text binary encoder', 'convert text to binary online'],
    live:           false,
  },
  {
    slug:           'palindrome-checker',
    name:           'Palindrome Checker',
    tagline:        'Check if text is a palindrome',
    description:    'Check if a word, phrase or sentence is a palindrome. Ignores spaces and punctuation.',
    seoTitle:       'Free Palindrome Checker Online — Test Words & Phrases | ToolKit',
    seoH1:          'Free Palindrome Checker Online',
    seoDescription: 'Check if any word, phrase or sentence is a palindrome. Ignores spaces and punctuation. Finds all palindromes in a larger text. Free, no signup.',
    category:       'Text & Writing',
    keywords:       ['palindrome checker', 'is it a palindrome', 'palindrome tester online', 'check palindrome'],
    live:           false,
  },
  {
    slug:           'text-statistics',
    name:           'Text Readability Analyser',
    tagline:        'Flesch–Kincaid, Gunning Fog and more',
    description:    'Analyse text readability with Flesch–Kincaid, Gunning Fog Index, SMOG and other scores.',
    seoTitle:       'Free Text Readability Analyser Online — Flesch Kincaid & More | ToolKit',
    seoH1:          'Free Text Readability Analyser Online',
    seoDescription: 'Analyse text readability with Flesch–Kincaid Grade Level, Flesch Reading Ease, Gunning Fog Index and SMOG. Find your target audience grade level. Free, no signup.',
    category:       'Text & Writing',
    keywords:       ['readability checker', 'flesch kincaid calculator', 'gunning fog index', 'readability score online', 'text readability analyser'],
    live:           false,
  },
  {
    slug:           'emoji-picker',
    name:           'Emoji Picker',
    tagline:        'Search and copy any emoji instantly',
    description:    'Browse, search and copy any emoji. Filter by category, search by name or keyword.',
    seoTitle:       'Free Emoji Picker Online — Search & Copy Emojis | ToolKit',
    seoH1:          'Free Emoji Picker Online',
    seoDescription: 'Search and copy any emoji instantly. Browse by category or search by name. Click to copy. Free online emoji picker — no signup, works on all devices.',
    category:       'Text & Writing',
    keywords:       ['emoji picker', 'emoji search online', 'copy emoji online', 'emoji keyboard online', 'find emoji by name'],
    live:           false,
  },
  {
    slug:           'superscript-converter',
    name:           'Superscript & Subscript Generator',
    tagline:        'Convert text to superscript or subscript Unicode',
    description:    'Convert text to Unicode superscript or subscript characters. Works anywhere — no HTML needed.',
    seoTitle:       'Free Superscript & Subscript Text Generator Online | ToolKit',
    seoH1:          'Free Superscript & Subscript Text Generator',
    seoDescription: 'Convert text to Unicode superscript (ˢᵘᵖᵉʳˢᶜʳⁱᵖᵗ) or subscript characters instantly. Works in social media, chat apps and anywhere plain text is supported. Free.',
    category:       'Text & Writing',
    keywords:       ['superscript generator', 'subscript generator', 'superscript text online', 'unicode superscript', 'small text generator'],
    live:           false,
  },
  {
    slug:           'text-to-html',
    name:           'Plain Text to HTML Converter',
    tagline:        'Convert plain text to formatted HTML',
    description:    'Convert plain text to HTML with proper paragraph tags, line breaks and entity encoding.',
    seoTitle:       'Free Plain Text to HTML Converter Online | ToolKit',
    seoH1:          'Free Plain Text to HTML Converter Online',
    seoDescription: 'Convert plain text to valid HTML instantly. Wraps paragraphs in <p> tags, encodes entities and handles line breaks. Free online text to HTML converter.',
    category:       'Text & Writing',
    keywords:       ['text to html converter', 'plain text to html', 'convert text to html online', 'html paragraph generator'],
    live:           false,
  },
  {
    slug:           'zalgo-generator',
    name:           'Zalgo Text Generator',
    tagline:        'Generate glitchy corrupted-looking text',
    description:    'Add Zalgo-style combining Unicode characters to text for a glitchy, corrupted aesthetic.',
    seoTitle:       'Free Zalgo Text Generator Online — Glitch & Corrupted Text | ToolKit',
    seoH1:          'Free Zalgo Glitch Text Generator Online',
    seoDescription: 'Generate Zalgo-style glitchy, corrupted-looking text using Unicode combining characters. Adjust intensity. Copy and paste anywhere. Free, no signup.',
    category:       'Text & Writing',
    keywords:       ['zalgo text generator', 'glitch text generator', 'corrupted text generator', 'creepy text generator'],
    live:           false,
  },
  {
    slug:           'fancy-text-generator',
    name:           'Fancy Text Generator',
    tagline:        'Stylish Unicode fonts for social media bios',
    description:    'Convert plain text to stylish Unicode fonts — bold, italic, cursive, bubble, double-struck and more.',
    seoTitle:       'Free Fancy Text Generator — Unicode Fonts for Instagram & Twitter | ToolKit',
    seoH1:          'Free Fancy Text Generator Online',
    seoDescription: 'Convert text to stylish Unicode fonts instantly — bold, italic, cursive, bubble, double-struck, fraktur and more. Works in Instagram bios, Twitter and Discord. Free.',
    category:       'Text & Writing',
    keywords:       ['fancy text generator', 'unicode font generator', 'stylish text generator', 'cool text generator', 'instagram font generator'],
    live:           false,
  },
  {
    slug:           'number-to-words',
    name:           'Number to Words Converter',
    tagline:        'Convert numbers to English words',
    description:    'Convert any number to English words — for cheques, invoices and formal documents.',
    seoTitle:       'Free Number to Words Converter Online — English & More | ToolKit',
    seoH1:          'Free Number to Words Converter Online',
    seoDescription: 'Convert any number to English words instantly. Supports integers up to trillions. Perfect for writing cheques, invoices and legal documents. Free, no signup.',
    category:       'Text & Writing',
    keywords:       ['number to words converter', 'number in words', 'spell out numbers', 'convert number to english words'],
    live:           false,
  },
  {
    slug:           'html-to-markdown',
    name:           'HTML to Markdown Converter',
    tagline:        'Convert HTML to clean Markdown',
    description:    'Paste HTML and get clean, readable Markdown output. Handles headings, lists, links, code blocks and tables.',
    seoTitle:       'Free HTML to Markdown Converter Online | ToolKit',
    seoH1:          'Free HTML to Markdown Converter Online',
    seoDescription: 'Convert HTML to Markdown instantly. Handles headings, paragraphs, lists, links, images, code blocks and tables. Free online HTML to Markdown tool — no signup.',
    category:       'Text & Writing',
    keywords:       ['html to markdown converter', 'html to markdown online', 'convert html to markdown', 'html markdown tool'],
    live:           false,
  },
  {
    slug:           'text-diff',
    name:           'Text Diff Checker',
    tagline:        'Compare two texts and highlight differences',
    description:    'Compare two blocks of text and see additions, deletions and changes highlighted.',
    seoTitle:       'Free Text Diff Checker Online — Compare Two Texts | ToolKit',
    seoH1:          'Free Text Diff Checker Online',
    seoDescription: 'Compare two texts and highlight differences instantly. See added, removed and changed lines color-coded. Free online diff tool — no signup required.',
    category:       'Text & Writing',
    keywords:       ['text diff checker', 'diff checker online', 'compare two texts', 'text compare online', 'text difference tool'],
    live:           true,
  },
  {
    slug:           'reading-time-calculator',
    name:           'Reading Time Calculator',
    tagline:        'Estimate reading time from word count',
    description:    'Calculate reading and speaking time from any text or word count.',
    seoTitle:       'Free Reading Time Calculator — Estimate Read Time Online | ToolKit',
    seoH1:          'Free Reading Time Calculator Online',
    seoDescription: 'Calculate how long it takes to read any text. Set your reading speed, get reading and speaking time estimates. Free online reading time calculator.',
    category:       'Text & Writing',
    keywords:       ['reading time calculator', 'read time estimator', 'words per minute calculator', 'article reading time'],
    live:           true,
  },
  {
    slug:           'random-text-generator',
    name:           'Random Text Generator',
    tagline:        'Generate random words, sentences and paragraphs',
    description:    'Generate random English words, sentences or paragraphs for testing.',
    seoTitle:       'Free Random Text Generator Online — Words, Sentences & Paragraphs | ToolKit',
    seoH1:          'Free Random Text Generator Online',
    seoDescription: 'Generate random words, sentences or paragraphs instantly. Choose length and style. Great for testing, mockups and development. Free, no signup.',
    category:       'Text & Writing',
    keywords:       ['random text generator', 'random word generator', 'random sentence generator', 'random paragraph generator'],
    live:           true,
  },
  /* ── Coming soon — Developer Tools ─────────────────── */
  {
    slug:           'json-to-csv',
    name:           'JSON to CSV Converter',
    tagline:        'Convert JSON arrays to CSV format',
    description:    'Convert JSON arrays to CSV. Handles nested objects, custom delimiters and download as .csv file.',
    seoTitle:       'Free JSON to CSV Converter Online — Convert JSON Arrays | ToolKit',
    seoH1:          'Free JSON to CSV Converter Online',
    seoDescription: 'Convert JSON arrays to CSV format instantly. Flatten nested objects, choose delimiter and download the result as a .csv file. Free, no signup, browser-based.',
    category:       'Developer Tools',
    keywords:       ['json to csv converter', 'convert json to csv', 'json csv online', 'export json as csv'],
    live:           false,
  },
  {
    slug:           'json-to-yaml',
    name:           'JSON to YAML Converter',
    tagline:        'Convert JSON to YAML and YAML to JSON',
    description:    'Convert JSON to YAML or YAML to JSON. Bidirectional, with syntax validation.',
    seoTitle:       'Free JSON to YAML Converter Online — Bidirectional | ToolKit',
    seoH1:          'Free JSON to YAML Converter Online',
    seoDescription: 'Convert JSON to YAML or YAML to JSON instantly. Validates syntax, handles nested structures. Free online JSON/YAML converter — no signup.',
    category:       'Developer Tools',
    keywords:       ['json to yaml', 'yaml to json', 'json yaml converter', 'convert json to yaml online', 'yaml converter'],
    live:           false,
  },
  {
    slug:           'xml-to-json',
    name:           'XML to JSON Converter',
    tagline:        'Convert XML to JSON and JSON to XML',
    description:    'Convert XML documents to JSON or JSON back to XML. Handles attributes and nested elements.',
    seoTitle:       'Free XML to JSON Converter Online — Bidirectional | ToolKit',
    seoH1:          'Free XML to JSON Converter Online',
    seoDescription: 'Convert XML to JSON or JSON back to XML instantly. Handles attributes, CDATA and nested elements. Free online XML/JSON converter — no signup.',
    category:       'Developer Tools',
    keywords:       ['xml to json converter', 'json to xml converter', 'xml json online', 'convert xml to json', 'xml parser online'],
    live:           false,
  },
  {
    slug:           'html-minifier',
    name:           'HTML Minifier',
    tagline:        'Minify and beautify HTML markup',
    description:    'Minify HTML by removing whitespace, comments and optional tags, or beautify compressed HTML.',
    seoTitle:       'Free HTML Minifier & Beautifier Online — Compress HTML | ToolKit',
    seoH1:          'Free HTML Minifier & Beautifier Online',
    seoDescription: 'Minify HTML to reduce page weight or beautify compressed HTML for readability. Removes comments and optional whitespace. Free online HTML minifier — no signup.',
    category:       'Developer Tools',
    keywords:       ['html minifier', 'minify html online', 'html compressor', 'html beautifier online', 'compress html'],
    live:           false,
  },
  {
    slug:           'javascript-minifier',
    name:           'JavaScript Minifier',
    tagline:        'Minify and compress JavaScript code',
    description:    'Minify JavaScript by removing whitespace and comments. Reduce bundle size without transpiling.',
    seoTitle:       'Free JavaScript Minifier Online — Compress JS Code | ToolKit',
    seoH1:          'Free JavaScript Minifier Online',
    seoDescription: 'Minify JavaScript code to reduce file size. Removes whitespace, comments and unnecessary characters. Free online JS minifier — no signup, works in browser.',
    category:       'Developer Tools',
    keywords:       ['javascript minifier', 'js minifier online', 'minify javascript online', 'compress js', 'js compressor'],
    live:           false,
  },
  {
    slug:           'sql-formatter',
    name:           'SQL Formatter',
    tagline:        'Format and beautify SQL queries',
    description:    'Format, indent and beautify SQL queries. Supports SELECT, INSERT, UPDATE, CREATE and more.',
    seoTitle:       'Free SQL Formatter Online — Beautify & Indent SQL Queries | ToolKit',
    seoH1:          'Free SQL Formatter & Beautifier Online',
    seoDescription: 'Format and beautify SQL queries instantly. Supports MySQL, PostgreSQL, SQLite and standard SQL. Proper indentation and keyword capitalisation. Free, no signup.',
    category:       'Developer Tools',
    keywords:       ['sql formatter', 'sql formatter online', 'format sql query', 'sql beautifier', 'sql pretty printer'],
    live:           false,
  },
  {
    slug:           'html-beautifier',
    name:           'HTML Beautifier',
    tagline:        'Format and indent HTML markup',
    description:    'Beautify and format HTML with proper indentation. Makes compressed or messy HTML readable.',
    seoTitle:       'Free HTML Beautifier Online — Format & Indent HTML | ToolKit',
    seoH1:          'Free HTML Beautifier Online',
    seoDescription: 'Beautify and format HTML markup with proper indentation. Paste compressed or messy HTML and get clean, readable output instantly. Free, no signup.',
    category:       'Developer Tools',
    keywords:       ['html beautifier', 'html formatter online', 'format html code', 'html pretty printer', 'html indenter'],
    live:           false,
  },
  {
    slug:           'number-base-converter',
    name:           'Number Base Converter',
    tagline:        'Convert between decimal, binary, hex and octal',
    description:    'Convert numbers between decimal, binary, hexadecimal and octal. Supports large integers.',
    seoTitle:       'Free Number Base Converter Online — Decimal, Binary, Hex, Octal | ToolKit',
    seoH1:          'Free Number Base Converter Online',
    seoDescription: 'Convert numbers between decimal, binary, hexadecimal and octal bases instantly. Supports large integers. Free online base converter — no signup.',
    category:       'Developer Tools',
    keywords:       ['number base converter', 'binary to decimal', 'hex to decimal', 'octal to decimal', 'decimal to binary converter', 'base converter online'],
    live:           false,
  },
  {
    slug:           'http-status-codes',
    name:           'HTTP Status Code Reference',
    tagline:        'Quick reference for all HTTP status codes',
    description:    'Searchable reference for all HTTP status codes — 1xx, 2xx, 3xx, 4xx and 5xx with descriptions.',
    seoTitle:       'HTTP Status Code Reference — All 1xx–5xx Codes Explained | ToolKit',
    seoH1:          'HTTP Status Code Reference',
    seoDescription: 'Quick reference for all HTTP status codes. Searchable list of 1xx informational, 2xx success, 3xx redirect, 4xx client error and 5xx server error codes. Free.',
    category:       'Developer Tools',
    keywords:       ['http status codes', 'http status code reference', '404 meaning', 'http error codes list', 'rest api status codes'],
    live:           false,
  },
  {
    slug:           'mime-types',
    name:           'MIME Types Reference',
    tagline:        'Searchable MIME type and file extension lookup',
    description:    'Find the MIME type for any file extension or find extensions for any MIME type.',
    seoTitle:       'MIME Types Reference & Lookup — File Extension to Content-Type | ToolKit',
    seoH1:          'MIME Types Reference & File Extension Lookup',
    seoDescription: 'Find the MIME type for any file extension or look up all extensions for a MIME type. Covers all common media types and application types. Free, searchable.',
    category:       'Developer Tools',
    keywords:       ['mime types list', 'mime type lookup', 'file extension mime type', 'content-type header values', 'mime type reference'],
    live:           false,
  },
  {
    slug:           'ascii-table',
    name:           'ASCII Table',
    tagline:        'Complete ASCII and Unicode character reference',
    description:    'Browse and search the full ASCII table with decimal, hex, octal, binary and HTML entity values.',
    seoTitle:       'ASCII Table — Full Character Reference with Hex, Binary & HTML | ToolKit',
    seoH1:          'Full ASCII Table & Character Reference',
    seoDescription: 'Complete ASCII table with decimal, hexadecimal, octal, binary and HTML entity values for every character. Searchable. Free online ASCII reference.',
    category:       'Developer Tools',
    keywords:       ['ascii table', 'ascii codes', 'ascii chart', 'ascii values', 'ascii character reference', 'html entities list'],
    live:           false,
  },
  {
    slug:           'color-name-finder',
    name:           'Color Name Finder',
    tagline:        'Find the nearest CSS color name for any hex',
    description:    'Enter any HEX or RGB color and find the nearest CSS named color and its distance.',
    seoTitle:       'Free Color Name Finder — Nearest CSS Named Color for Any Hex | ToolKit',
    seoH1:          'Free Color Name Finder Online',
    seoDescription: 'Enter any HEX or RGB color and instantly find the nearest CSS named color. See color distance and all 148 CSS named colors. Free, no signup.',
    category:       'Developer Tools',
    keywords:       ['color name finder', 'css color names', 'hex to color name', 'nearest css color', 'color name from hex'],
    live:           false,
  },
  {
    slug:           'unicode-lookup',
    name:           'Unicode Character Lookup',
    tagline:        'Search Unicode code points, names and blocks',
    description:    'Search Unicode characters by name, code point, or category. Get HTML entity and UTF-8 encoding.',
    seoTitle:       'Free Unicode Character Lookup — Code Points, Names & Encodings | ToolKit',
    seoH1:          'Free Unicode Character Lookup',
    seoDescription: 'Search Unicode characters by name, code point or block. Get Unicode code point, UTF-8 bytes, HTML entity and CSS escape for any character. Free, no signup.',
    category:       'Developer Tools',
    keywords:       ['unicode lookup', 'unicode character finder', 'unicode code point search', 'utf8 character lookup'],
    live:           false,
  },
  {
    slug:           'gitignore-generator',
    name:           '.gitignore Generator',
    tagline:        'Generate .gitignore files for any stack',
    description:    'Generate .gitignore files for any combination of languages, frameworks and editors.',
    seoTitle:       'Free .gitignore Generator Online — Any Language & Framework | ToolKit',
    seoH1:          'Free .gitignore Generator Online',
    seoDescription: 'Generate .gitignore files for any combination of programming languages, frameworks and IDEs. Node.js, Python, Java, macOS, VS Code and more. Free, no signup.',
    category:       'Developer Tools',
    keywords:       ['gitignore generator', 'gitignore file generator', 'create gitignore online', '.gitignore template'],
    live:           false,
  },
  {
    slug:           'robots-txt-generator',
    name:           'Robots.txt Generator',
    tagline:        'Generate robots.txt files for your site',
    description:    'Generate a robots.txt file with rules for common bots, crawl delays and sitemap declaration.',
    seoTitle:       'Free Robots.txt Generator Online — SEO Crawler Rules | ToolKit',
    seoH1:          'Free Robots.txt Generator Online',
    seoDescription: 'Generate a robots.txt file with allow/disallow rules for Googlebot, Bingbot and more. Set crawl delays and declare your sitemap URL. Free, no signup.',
    category:       'Developer Tools',
    keywords:       ['robots.txt generator', 'robots txt creator online', 'create robots txt file', 'seo robots txt tool'],
    live:           false,
  },
  {
    slug:           'image-to-base64',
    name:           'Image to Base64 Converter',
    tagline:        'Convert images to Base64 data URLs',
    description:    'Upload an image and get its Base64 data URL for use in CSS, HTML and JavaScript.',
    seoTitle:       'Free Image to Base64 Converter Online — Data URL Generator | ToolKit',
    seoH1:          'Free Image to Base64 Converter Online',
    seoDescription: 'Convert JPEG, PNG, WebP and SVG images to Base64 data URLs. Copy the CSS or HTML data URL for embedding images without HTTP requests. Free, browser-based.',
    category:       'Developer Tools',
    keywords:       ['image to base64', 'image base64 converter', 'base64 image encoder', 'convert image to base64 online', 'data url generator'],
    live:           false,
  },
  {
    slug:           'css-unit-converter',
    name:           'CSS Unit Converter',
    tagline:        'Convert px, rem, em, vw, vh and more',
    description:    'Convert CSS units: px, rem, em, %, vw, vh and pt. Set your root font size for accurate rem conversion.',
    seoTitle:       'Free CSS Unit Converter Online — px to rem, em, vw & More | ToolKit',
    seoH1:          'Free CSS Unit Converter Online',
    seoDescription: 'Convert CSS units instantly — px to rem, rem to px, em, %, vw, vh and pt. Set your base font size for accurate calculations. Free online CSS unit tool.',
    category:       'Developer Tools',
    keywords:       ['css unit converter', 'px to rem converter', 'rem to px', 'px to em', 'css units calculator'],
    live:           false,
  },
  {
    slug:           'semver-comparator',
    name:           'Semver Comparator',
    tagline:        'Compare semantic version strings',
    description:    'Compare two semver version strings. Check if one is greater, equal or less. Validate semver format.',
    seoTitle:       'Free Semver Comparator Online — Compare Semantic Versions | ToolKit',
    seoH1:          'Free Semantic Version Comparator Online',
    seoDescription: 'Compare semantic version strings instantly. Check if a version is greater, less or equal. Validate semver format. Free online semver tool — no signup.',
    category:       'Developer Tools',
    keywords:       ['semver comparator', 'semantic version comparator', 'compare semver', 'version number comparison', 'semver validator'],
    live:           false,
  },
  {
    slug:           'json-schema-generator',
    name:           'JSON Schema Generator',
    tagline:        'Generate JSON Schema from any JSON sample',
    description:    'Paste a JSON document and generate a JSON Schema (Draft-07) automatically.',
    seoTitle:       'Free JSON Schema Generator Online — Draft-07 from Sample JSON | ToolKit',
    seoH1:          'Free JSON Schema Generator Online',
    seoDescription: 'Generate a JSON Schema (Draft-07) automatically from any sample JSON. Infers types, required fields and array items. Free online JSON Schema tool — no signup.',
    category:       'Developer Tools',
    keywords:       ['json schema generator', 'generate json schema from json', 'json schema online', 'json schema draft 7'],
    live:           false,
  },
  {
    slug:           'mock-data-generator',
    name:           'Mock Data Generator',
    tagline:        'Generate realistic fake data for testing',
    description:    'Generate fake names, emails, addresses, phone numbers, dates and more in JSON or CSV.',
    seoTitle:       'Free Mock Data Generator Online — Fake Names, Emails, JSON | ToolKit',
    seoH1:          'Free Mock Data Generator Online',
    seoDescription: 'Generate realistic fake data for testing — names, emails, phone numbers, addresses, dates and UUIDs. Export as JSON or CSV. Free, browser-based, no signup.',
    category:       'Developer Tools',
    keywords:       ['mock data generator', 'fake data generator', 'test data generator', 'dummy data generator', 'random data generator'],
    live:           false,
  },
  {
    slug:           'toml-to-json',
    name:           'TOML to JSON Converter',
    tagline:        'Convert TOML config files to JSON',
    description:    'Convert TOML configuration files to JSON or JSON back to TOML with syntax validation.',
    seoTitle:       'Free TOML to JSON Converter Online — Config File Converter | ToolKit',
    seoH1:          'Free TOML to JSON Converter Online',
    seoDescription: 'Convert TOML configuration files to JSON or JSON back to TOML. Validates syntax and handles all TOML data types. Free online TOML converter — no signup.',
    category:       'Developer Tools',
    keywords:       ['toml to json', 'json to toml', 'toml converter online', 'toml json online', 'config file converter'],
    live:           false,
  },
  {
    slug:           'csv-viewer',
    name:           'CSV Viewer & Editor',
    tagline:        'Preview and edit CSV data in a table',
    description:    'Upload or paste CSV data and view it as an interactive table. Sort, filter and edit cells.',
    seoTitle:       'Free CSV Viewer & Editor Online — View CSV as Table | ToolKit',
    seoH1:          'Free CSV Viewer & Editor Online',
    seoDescription: 'View and edit CSV data as an interactive table. Sort columns, filter rows, edit cells and download the modified CSV. Free online CSV viewer — no signup.',
    category:       'Developer Tools',
    keywords:       ['csv viewer', 'csv table viewer online', 'view csv file online', 'csv editor online', 'open csv online'],
    live:           false,
  },
  {
    slug:           'user-agent-parser',
    name:           'User-Agent Parser',
    tagline:        'Parse and decode browser user-agent strings',
    description:    'Parse user-agent strings to extract browser, OS, device type and engine information.',
    seoTitle:       'Free User-Agent Parser Online — Browser & OS Detection | ToolKit',
    seoH1:          'Free User-Agent Parser Online',
    seoDescription: 'Parse any user-agent string and extract browser name, version, OS, device type and rendering engine. See your own UA or paste any string. Free, no signup.',
    category:       'Developer Tools',
    keywords:       ['user agent parser', 'user agent string parser', 'browser detection online', 'ua parser', 'what is my user agent'],
    live:           false,
  },
  {
    slug:           'ip-cidr-calculator',
    name:           'IP / CIDR Calculator',
    tagline:        'Calculate subnet ranges, masks and hosts',
    description:    'Enter an IP address and CIDR prefix to get subnet range, broadcast address, usable hosts and more.',
    seoTitle:       'Free IP CIDR Subnet Calculator Online — Network Range & Hosts | ToolKit',
    seoH1:          'Free IP / CIDR Subnet Calculator Online',
    seoDescription: 'Calculate subnet information from any IP/CIDR notation. Get network address, broadcast, subnet mask, range and usable host count. Free online subnet calculator.',
    category:       'Developer Tools',
    keywords:       ['cidr calculator', 'subnet calculator online', 'ip cidr calculator', 'network range calculator', 'ip subnet mask calculator'],
    live:           false,
  },
  {
    slug:           'jwt-generator',
    name:           'JWT Generator',
    tagline:        'Generate and sign JWT tokens',
    description:    'Create and sign JWT tokens with HS256, HS384 or HS512. Set custom claims and expiry.',
    seoTitle:       'Free JWT Generator Online — Sign JWTs with HS256 & HS512 | ToolKit',
    seoH1:          'Free JWT Generator Online',
    seoDescription: 'Generate and sign JWT tokens with HS256, HS384 or HS512. Set custom payload claims, issue time and expiry. Free online JWT generator — no signup.',
    category:       'Developer Tools',
    keywords:       ['jwt generator', 'generate jwt token online', 'jwt token creator', 'sign jwt online', 'json web token generator'],
    live:           false,
  },
  {
    slug:           'htaccess-generator',
    name:           '.htaccess Generator',
    tagline:        'Generate Apache .htaccess rules',
    description:    'Generate Apache .htaccess rules for redirects, HTTPS enforcement, caching headers and more.',
    seoTitle:       'Free .htaccess Generator Online — Apache Rules & Redirects | ToolKit',
    seoH1:          'Free Apache .htaccess Generator Online',
    seoDescription: 'Generate Apache .htaccess rules for HTTPS redirects, www/non-www enforcement, browser caching, CORS headers and more. Free online .htaccess generator.',
    category:       'Developer Tools',
    keywords:       ['htaccess generator', '.htaccess redirect generator', 'apache htaccess tool', 'htaccess rules generator'],
    live:           false,
  },
  {
    slug:           'svg-optimizer',
    name:           'SVG Optimizer',
    tagline:        'Optimize and compress SVG files',
    description:    'Paste SVG markup and remove unnecessary attributes, metadata and whitespace to reduce file size.',
    seoTitle:       'Free SVG Optimizer Online — Compress & Clean SVG Files | ToolKit',
    seoH1:          'Free SVG Optimizer Online',
    seoDescription: 'Optimize and compress SVG files by removing unnecessary attributes, comments and metadata. Reduce SVG file size without visual quality loss. Free, browser-based.',
    category:       'Developer Tools',
    keywords:       ['svg optimizer', 'svg compressor online', 'optimize svg online', 'svgo online', 'minify svg'],
    live:           false,
  },
  {
    slug:           'color-contrast-checker',
    name:           'Color Contrast Checker',
    tagline:        'WCAG 2.1 AA/AAA contrast ratio checker',
    description:    'Check foreground and background color contrast ratio for WCAG 2.1 AA and AAA accessibility compliance.',
    seoTitle:       'Free Color Contrast Checker — WCAG AA & AAA Compliance | ToolKit',
    seoH1:          'Free WCAG Color Contrast Checker Online',
    seoDescription: 'Check color contrast ratio for WCAG 2.1 AA and AAA accessibility compliance. Enter foreground and background colors. Get pass/fail result and suggestions. Free.',
    category:       'Developer Tools',
    keywords:       ['color contrast checker', 'wcag contrast checker', 'accessibility contrast ratio', 'aa contrast checker', 'web accessibility color tool'],
    live:           false,
  },
  {
    slug:           'markdown-to-html',
    name:           'Markdown to HTML Exporter',
    tagline:        'Export Markdown as clean HTML',
    description:    'Convert Markdown to HTML with syntax highlighting for code blocks. Download or copy the output.',
    seoTitle:       'Free Markdown to HTML Exporter Online — With Code Highlighting | ToolKit',
    seoH1:          'Free Markdown to HTML Exporter Online',
    seoDescription: 'Convert Markdown to HTML with syntax-highlighted code blocks. Download the output as an .html file or copy it. Free online Markdown exporter — no signup.',
    category:       'Developer Tools',
    keywords:       ['markdown to html', 'markdown to html converter', 'export markdown as html', 'markdown html export online'],
    live:           false,
  },
  {
    slug:           'lorem-json',
    name:           'Lorem JSON Generator',
    tagline:        'Generate JSON with realistic random data',
    description:    'Generate JSON arrays with realistic random fields — names, emails, dates, IDs and more.',
    seoTitle:       'Free Lorem JSON Generator Online — Random JSON Data | ToolKit',
    seoH1:          'Free Lorem JSON Generator Online',
    seoDescription: 'Generate JSON arrays filled with realistic random data. Choose fields: name, email, date, UUID, boolean and more. Download as .json. Free, no signup.',
    category:       'Developer Tools',
    keywords:       ['json data generator', 'lorem json', 'random json generator', 'fake json api', 'mock json generator'],
    live:           false,
  },
  {
    slug:           'regex-tester',
    name:           'Regex Tester',
    tagline:        'Test and debug regular expressions live',
    description:    'Test regular expressions with live match highlighting. Supports JavaScript and Python.',
    seoTitle:       'Free Regex Tester Online — Test & Debug Regular Expressions | ToolKit',
    seoH1:          'Free Regex Tester Online',
    seoDescription: 'Test and debug regular expressions with live match highlighting. Supports JavaScript regex flags. See matches, groups and captures instantly. Free, no signup.',
    category:       'Developer Tools',
    keywords:       ['regex tester', 'regex tester online', 'regular expression tester', 'regex checker', 'regex debugger online'],
    live:           true,
  },
  {
    slug:           'timestamp-converter',
    name:           'Timestamp Converter',
    tagline:        'Convert Unix timestamps to human-readable dates',
    description:    'Convert Unix timestamps to dates and back. Supports seconds and milliseconds.',
    seoTitle:       'Free Unix Timestamp Converter Online — Epoch to Date | ToolKit',
    seoH1:          'Free Unix Timestamp Converter Online',
    seoDescription: 'Convert Unix/epoch timestamps to human-readable dates and back. Supports seconds and milliseconds. Shows current timestamp live. Free online timestamp converter.',
    category:       'Developer Tools',
    keywords:       ['timestamp converter', 'unix timestamp converter', 'epoch converter', 'epoch to date', 'timestamp to date online'],
    live:           true,
  },
  {
    slug:           'cron-generator',
    name:           'Cron Expression Generator',
    tagline:        'Build and validate cron job schedules',
    description:    'Generate cron expressions visually and see next execution times in plain English.',
    seoTitle:       'Free Cron Expression Generator & Validator Online | ToolKit',
    seoH1:          'Free Cron Expression Generator Online',
    seoDescription: 'Build cron expressions visually, validate syntax and see next 10 run times in plain English. Free cron job generator — no signup, works in browser.',
    category:       'Developer Tools',
    keywords:       ['cron generator', 'cron expression generator', 'cron job generator online', 'crontab generator', 'cron expression validator'],
    live:           true,
  },
  {
    slug:           'css-minifier',
    name:           'CSS Minifier',
    tagline:        'Minify and beautify CSS code',
    description:    'Minify or beautify CSS code. Remove comments, whitespace and optimize output.',
    seoTitle:       'Free CSS Minifier & Beautifier Online — Compress CSS | ToolKit',
    seoH1:          'Free CSS Minifier & Beautifier Online',
    seoDescription: 'Minify CSS to reduce file size or beautify compressed CSS for readability. Removes comments and whitespace. Free online CSS minifier — no signup.',
    category:       'Developer Tools',
    keywords:       ['css minifier', 'css minifier online', 'minify css', 'css compressor', 'css beautifier online'],
    live:           false,
  },
  {
    slug:           'html-entities',
    name:           'HTML Entities Encoder',
    tagline:        'Encode and decode HTML entities',
    description:    'Encode special characters as HTML entities or decode HTML entities back to text.',
    seoTitle:       'Free HTML Entities Encoder & Decoder Online | ToolKit',
    seoH1:          'Free HTML Entities Encoder & Decoder',
    seoDescription: 'Encode special characters as HTML entities or decode HTML entities back to plain text. Free online HTML entity encoder — no signup, instant results.',
    category:       'Developer Tools',
    keywords:       ['html entities encoder', 'html entity decoder', 'html encode online', 'html escape online', 'html entities converter'],
    live:           false,
  },

  /* ── Value Converter ───────────────────────────────── */
  {
    slug:           'length-converter',
    name:           'Length Converter',
    tagline:        'Convert metres, feet, inches, miles and more',
    description:    'Convert length between metres, kilometres, miles, feet, inches, centimetres, yards and nautical miles.',
    seoTitle:       'Free Length Converter Online — Metres, Feet, Inches, Miles | ToolKit',
    seoH1:          'Free Length Converter Online',
    seoDescription: 'Convert length between metres, kilometres, miles, feet, inches, centimetres and yards instantly. All units update as you type. Free length unit converter.',
    category:       'Value Converter',
    keywords:       ['length converter', 'metres to feet', 'km to miles', 'inches to cm', 'unit of length converter', 'distance converter'],
    live:           false,
  },
  {
    slug:           'weight-converter',
    name:           'Weight Converter',
    tagline:        'Convert kg, lbs, grams, ounces and more',
    description:    'Convert weight and mass between kilograms, pounds, grams, ounces, stones, tonnes and more.',
    seoTitle:       'Free Weight Converter Online — kg to lbs, grams to ounces | ToolKit',
    seoH1:          'Free Weight & Mass Converter Online',
    seoDescription: 'Convert weight between kilograms, pounds, grams, ounces, stones and tonnes instantly. All units update as you type. Free online weight converter.',
    category:       'Value Converter',
    keywords:       ['weight converter', 'kg to lbs', 'pounds to kilograms', 'grams to ounces', 'mass converter online'],
    live:           false,
  },
  {
    slug:           'temperature-converter',
    name:           'Temperature Converter',
    tagline:        'Convert Celsius, Fahrenheit and Kelvin',
    description:    'Convert temperature between Celsius, Fahrenheit and Kelvin instantly.',
    seoTitle:       'Free Temperature Converter — Celsius to Fahrenheit, Kelvin | ToolKit',
    seoH1:          'Free Temperature Converter Online',
    seoDescription: 'Convert temperature between Celsius, Fahrenheit and Kelvin instantly. All units update as you type. Free online temperature converter — no signup.',
    category:       'Value Converter',
    keywords:       ['temperature converter', 'celsius to fahrenheit', 'fahrenheit to celsius', 'kelvin to celsius', 'temperature unit converter'],
    live:           false,
  },
  {
    slug:           'area-converter',
    name:           'Area Converter',
    tagline:        'Convert m², ft², acres, hectares and more',
    description:    'Convert area between square metres, square feet, acres, hectares, square kilometres and square miles.',
    seoTitle:       'Free Area Converter Online — m², ft², Acres & Hectares | ToolKit',
    seoH1:          'Free Area Converter Online',
    seoDescription: 'Convert area between square metres, square feet, acres, hectares, square kilometres and square miles. All units update as you type. Free area unit converter.',
    category:       'Value Converter',
    keywords:       ['area converter', 'square feet to square metres', 'acres to hectares', 'area unit converter online'],
    live:           false,
  },
  {
    slug:           'volume-converter',
    name:           'Volume Converter',
    tagline:        'Convert litres, gallons, cups, ml and more',
    description:    'Convert volume between litres, US gallons, cups, millilitres, fluid ounces and cubic metres.',
    seoTitle:       'Free Volume Converter Online — Litres, Gallons, Cups, ml | ToolKit',
    seoH1:          'Free Volume Converter Online',
    seoDescription: 'Convert volume between litres, US gallons, imperial gallons, cups, millilitres and fluid ounces. All units update as you type. Free volume converter.',
    category:       'Value Converter',
    keywords:       ['volume converter', 'litres to gallons', 'cups to ml', 'fluid ounce converter', 'volume unit converter'],
    live:           false,
  },
  {
    slug:           'speed-converter',
    name:           'Speed Converter',
    tagline:        'Convert km/h, mph, m/s, knots and more',
    description:    'Convert speed between km/h, mph, m/s, knots and ft/s instantly.',
    seoTitle:       'Free Speed Converter Online — km/h, mph, m/s, Knots | ToolKit',
    seoH1:          'Free Speed Converter Online',
    seoDescription: 'Convert speed between kilometres per hour, miles per hour, metres per second, knots and feet per second. All units update as you type. Free speed converter.',
    category:       'Value Converter',
    keywords:       ['speed converter', 'km/h to mph', 'mph to km/h', 'knots to mph', 'speed unit converter online'],
    live:           false,
  },
  {
    slug:           'data-storage-converter',
    name:           'Data Storage Converter',
    tagline:        'Convert bytes, KB, MB, GB, TB and more',
    description:    'Convert digital storage units between bits, bytes, kilobytes, megabytes, gigabytes and terabytes.',
    seoTitle:       'Free Data Storage Converter Online — bytes, KB, MB, GB, TB | ToolKit',
    seoH1:          'Free Data Storage Unit Converter Online',
    seoDescription: 'Convert data storage units between bits, bytes, KB, MB, GB, TB and PB. Supports both SI (1000-based) and binary (1024-based) units. Free, no signup.',
    category:       'Value Converter',
    keywords:       ['data storage converter', 'bytes to megabytes', 'mb to gb converter', 'gigabyte converter', 'file size converter'],
    live:           false,
  },
  {
    slug:           'pressure-converter',
    name:           'Pressure Converter',
    tagline:        'Convert Pascal, bar, PSI, atm and mmHg',
    description:    'Convert pressure between Pascal, bar, PSI, atmospheres, kilopascals and mmHg.',
    seoTitle:       'Free Pressure Converter Online — Pascal, PSI, Bar, atm | ToolKit',
    seoH1:          'Free Pressure Converter Online',
    seoDescription: 'Convert pressure between Pascal, bar, PSI, atmospheres, kilopascals and mmHg. All units update as you type. Free online pressure unit converter.',
    category:       'Value Converter',
    keywords:       ['pressure converter', 'psi to bar', 'pascal to bar', 'pressure unit converter', 'atm to psi'],
    live:           false,
  },
  {
    slug:           'energy-converter',
    name:           'Energy Converter',
    tagline:        'Convert joules, calories, kWh, BTU and more',
    description:    'Convert energy and work between joules, kilojoules, calories, kilocalories, kWh and BTU.',
    seoTitle:       'Free Energy Converter Online — Joules, Calories, kWh, BTU | ToolKit',
    seoH1:          'Free Energy Converter Online',
    seoDescription: 'Convert energy between joules, kilojoules, calories, kilocalories, kilowatt-hours and BTU. All units update as you type. Free online energy unit converter.',
    category:       'Value Converter',
    keywords:       ['energy converter', 'joules to calories', 'kwh to joules', 'btu to joules', 'energy unit converter'],
    live:           false,
  },
  {
    slug:           'frequency-converter',
    name:           'Frequency Converter',
    tagline:        'Convert Hz, kHz, MHz, GHz and RPM',
    description:    'Convert frequency between hertz, kilohertz, megahertz, gigahertz and RPM.',
    seoTitle:       'Free Frequency Converter Online — Hz, kHz, MHz, GHz | ToolKit',
    seoH1:          'Free Frequency Converter Online',
    seoDescription: 'Convert frequency between Hz, kHz, MHz, GHz and RPM. All units update as you type. Free online frequency unit converter — no signup.',
    category:       'Value Converter',
    keywords:       ['frequency converter', 'hz to mhz', 'mhz to ghz', 'frequency unit converter', 'hertz converter'],
    live:           false,
  },
  {
    slug:           'angle-converter',
    name:           'Angle Converter',
    tagline:        'Convert degrees, radians and gradians',
    description:    'Convert angles between degrees, radians, gradians and turns.',
    seoTitle:       'Free Angle Converter Online — Degrees, Radians, Gradians | ToolKit',
    seoH1:          'Free Angle Converter Online',
    seoDescription: 'Convert angles between degrees, radians, gradians and turns instantly. All units update as you type. Free online angle unit converter — no signup.',
    category:       'Value Converter',
    keywords:       ['angle converter', 'degrees to radians', 'radians to degrees', 'angle unit converter online'],
    live:           false,
  },
  {
    slug:           'fuel-economy-converter',
    name:           'Fuel Economy Converter',
    tagline:        'Convert MPG, L/100km and km/L',
    description:    'Convert fuel economy between miles per gallon, litres per 100 km and kilometres per litre.',
    seoTitle:       'Free Fuel Economy Converter — MPG, L/100km, km/L | ToolKit',
    seoH1:          'Free Fuel Economy Converter Online',
    seoDescription: 'Convert fuel efficiency between mpg (US), mpg (UK), L/100km and km/L instantly. All units update as you type. Free online fuel economy converter.',
    category:       'Value Converter',
    keywords:       ['fuel economy converter', 'mpg to l/100km', 'l/100km to mpg', 'fuel consumption converter', 'km per litre converter'],
    live:           false,
  },
  {
    slug:           'pixel-rem-converter',
    name:           'Pixel ↔ REM Converter',
    tagline:        'Convert px to rem and rem to px',
    description:    'Convert CSS pixel values to rem and vice versa. Set a custom base font size.',
    seoTitle:       'Free Pixel to REM Converter — px ↔ rem with Custom Base Size | ToolKit',
    seoH1:          'Free Pixel to REM Converter Online',
    seoDescription: 'Convert CSS pixels to rem and rem to pixels instantly. Set your base font size (default 16px). Great for responsive CSS development. Free, no signup.',
    category:       'Value Converter',
    keywords:       ['px to rem converter', 'rem to px converter', 'pixel rem conversion', 'css rem calculator', 'font size rem calculator'],
    live:           false,
  },
  {
    slug:           'roman-numeral-converter',
    name:           'Roman Numeral Converter',
    tagline:        'Convert numbers to Roman numerals and back',
    description:    'Convert Arabic numbers to Roman numerals or Roman numerals back to numbers.',
    seoTitle:       'Free Roman Numeral Converter Online — Arabic to Roman & Back | ToolKit',
    seoH1:          'Free Roman Numeral Converter Online',
    seoDescription: 'Convert Arabic numbers to Roman numerals or decode Roman numerals back to numbers. Supports 1–3999. Free online Roman numeral converter — no signup.',
    category:       'Value Converter',
    keywords:       ['roman numeral converter', 'arabic to roman numerals', 'roman numeral to number', 'roman numerals online'],
    live:           false,
  },
  {
    slug:           'cooking-converter',
    name:           'Cooking Measurement Converter',
    tagline:        'Convert cups, tablespoons, grams and ml',
    description:    'Convert cooking measurements between cups, tablespoons, teaspoons, grams, ml and fluid ounces.',
    seoTitle:       'Free Cooking Measurement Converter — Cups, Grams, ml | ToolKit',
    seoH1:          'Free Cooking Measurement Converter Online',
    seoDescription: 'Convert cooking measurements between cups, tablespoons, teaspoons, millilitres, grams and fluid ounces. Free online cooking converter — no signup.',
    category:       'Value Converter',
    keywords:       ['cooking measurement converter', 'cups to grams', 'tablespoons to ml', 'cooking unit converter', 'recipe measurement converter'],
    live:           false,
  },
  {
    slug:           'currency-converter',
    name:           'Currency Converter',
    tagline:        'Convert between world currencies with live rates',
    description:    'Convert between 150+ world currencies using live exchange rates.',
    seoTitle:       'Free Currency Converter Online — Live Exchange Rates | ToolKit',
    seoH1:          'Free Currency Converter Online',
    seoDescription: 'Convert between 150+ world currencies with live exchange rates. Fast, free and ad-free. Free online currency converter — no signup required.',
    category:       'Value Converter',
    keywords:       ['currency converter', 'live currency converter', 'exchange rate calculator', 'usd to eur', 'foreign exchange converter'],
    live:           false,
  },
  {
    slug:           'time-converter',
    name:           'Time Converter',
    tagline:        'Convert seconds, minutes, hours, days, weeks, years',
    description:    'Convert any time value between seconds, minutes, hours, days, weeks, months and years instantly.',
    seoTitle:       'Free Time Converter Online — Seconds to Days, Weeks, Years | ToolKit',
    seoH1:          'Free Time Converter Online',
    seoDescription: 'Convert time values instantly between seconds, minutes, hours, days, weeks, months and years. Enter any value and get all units at once. Free, browser-based, no signup.',
    category:       'Value Converter',
    keywords:       ['time converter', 'seconds to days', 'seconds to years', 'days to seconds', 'time unit converter', 'convert seconds to hours', 'convert days to weeks'],
    live:           true,
  },

  /* ── Coming soon — Design ───────────────────────────── */
  {
    slug:           'color-converter',
    name:           'Color Converter',
    tagline:        'Convert between HEX, RGB, HSL, HSV and CMYK',
    description:    'Convert colors between HEX, RGB, HSL, HSV and CMYK instantly. Live preview, CSS output, one-click copy.',
    seoTitle:       'Free Color Converter — HEX to RGB, HSL, CMYK & More | ToolKit',
    seoH1:          'Free Color Converter Online',
    seoDescription: 'Convert colors between HEX, RGB, HSL, HSV and CMYK instantly. Get CSS-ready output, live color preview, and one-click copy. Free, browser-based, no signup.',
    category:       'Design',
    keywords:       ['color converter', 'hex to rgb', 'rgb to hex', 'hsl to hex', 'hex to hsl', 'rgb to hsl', 'cmyk to rgb', 'color format converter', 'css color converter'],
    live:           true,
  },
  {
    slug:           'gradient-generator',
    name:           'CSS Gradient Generator',
    tagline:        'Create CSS gradients with live preview',
    description:    'Generate linear and radial CSS gradients visually. Copy the CSS output.',
    seoTitle:       'Free CSS Gradient Generator Online — Linear & Radial Gradients | ToolKit',
    seoH1:          'Free CSS Gradient Generator Online',
    seoDescription: 'Create beautiful linear and radial CSS gradients with live preview. Adjust colors, angle and stops. Copy the CSS output. Free online gradient generator.',
    category:       'Design',
    keywords:       ['css gradient generator', 'gradient generator online', 'linear gradient generator', 'css gradient maker', 'gradient css tool'],
    live:           false,
  },
  {
    slug:           'box-shadow-generator',
    name:           'Box Shadow Generator',
    tagline:        'Create CSS box shadows with live preview',
    description:    'Generate CSS box-shadow values visually with real-time preview.',
    seoTitle:       'Free CSS Box Shadow Generator Online — Live Preview | ToolKit',
    seoH1:          'Free CSS Box Shadow Generator Online',
    seoDescription: 'Create CSS box shadows visually with live preview. Adjust blur, spread, color and inset. Copy the CSS. Free online box shadow generator — no signup.',
    category:       'Design',
    keywords:       ['box shadow generator', 'css box shadow generator', 'box shadow css online', 'css shadow tool'],
    live:           false,
  },
  {
    slug:           'favicon-generator',
    name:           'Favicon Generator',
    tagline:        'Generate favicons from text or emoji',
    description:    'Create favicons from text, emoji or simple icons. Download as ICO and PNG.',
    seoTitle:       'Free Favicon Generator Online — Create Favicons from Text & Emoji | ToolKit',
    seoH1:          'Free Favicon Generator Online',
    seoDescription: 'Generate favicons from text, letters or emoji. Download as ICO (16×16, 32×32) and PNG (192×192). Free online favicon generator — no signup, instant download.',
    category:       'Design',
    keywords:       ['favicon generator', 'favicon generator online', 'create favicon', 'favicon maker', 'free favicon generator'],
    live:           true,
  },
];

/* ── Helpers ──────────────────────────────────────────── */
export const getLiveTools  = () => TOOLS.filter(t => t.live);
export const getSoonTools  = () => TOOLS.filter(t => !t.live);
export const getFeatured   = () => TOOLS.find(t => t.featured);
export const getBySlug     = (slug: string) => TOOLS.find(t => t.slug === slug);
export const getLiveSlugs  = () => getLiveTools().map(t => t.slug);

export const getVariant = (toolSlug: string, variantSlug: string) => {
  const tool = getBySlug(toolSlug);
  return tool?.variants?.find(v => v.slug === variantSlug) ?? null;
};

export const getAllVariantPaths = () => {
  const paths: { params: { slug: string; variant: string } }[] = [];
  for (const tool of getLiveTools()) {
    for (const v of tool.variants ?? []) {
      paths.push({ params: { slug: tool.slug, variant: v.slug } });
    }
  }
  return paths;
};

export const getByCategory = () => {
  const map = new Map<string, ToolMeta[]>();
  for (const tool of TOOLS) {
    if (!map.has(tool.category)) map.set(tool.category, []);
    map.get(tool.category)!.push(tool);
  }
  return map;
};