import { FaqItem } from '@/lib/types';

export const faq: FaqItem[] = [
  {
    q: 'What is ROT13 and how does it work?',
    a: `ROT13 (rotate by 13) is a simple letter substitution cipher that replaces each letter in the Latin alphabet with the letter 13 positions after it, wrapping around at the end of the alphabet. For example, A becomes N, B becomes O, C becomes P, and so on until M becomes Z. Then N becomes A, O becomes B, and the pattern continues back to Z becoming M. Because the Latin alphabet has exactly 26 letters — twice 13 — applying ROT13 twice returns you to the original text. This self-inverse property means applying the cipher is the same as reversing it. Non-letter characters — digits, spaces, punctuation, symbols, and non-Latin Unicode — pass through completely unchanged. Only the 26 standard Latin letters in both uppercase and lowercase are rotated. The rotation is case-preserving: lowercase letters stay lowercase, uppercase stay uppercase. ROT13 is trivially reversible by anyone who knows the scheme, which is exactly the point — it is not intended as real encryption.`,
  },
  {
    q: 'Why is ROT13 not considered real encryption?',
    a: `Real encryption aims to protect information from unauthorized access even when an attacker knows the encryption algorithm and has significant computing resources. ROT13 fails this test comprehensively. It has effectively zero security: any person who knows or guesses that ROT13 was used can decode the message instantly by hand. There is no key — everyone uses the same fixed shift of 13 positions. The cipher is unconditional: knowing one ROT13-encoded letter immediately reveals the encoding for all 13 other letter pairs. Unlike secure encryption algorithms such as AES-256, RSA, or ChaCha20 that use large cryptographic keys and complex mathematical operations, ROT13 uses only a simple arithmetic shift. The letter frequency distribution in ROT13 text matches English but shifted by 13 positions, making it breakable by simple frequency analysis with no knowledge of the algorithm. ROT13 is designed for obfuscation — making text unreadable at a casual glance — not for security.`,
  },
  {
    q: 'How is ROT13 different from other Caesar ciphers?',
    a: `A Caesar cipher is any cipher that shifts letters by a fixed number of positions in the alphabet, named after Julius Caesar who reportedly used a shift of 3 for military communications. ROT13 is a Caesar cipher with a specific shift of 13. What makes ROT13 unique among Caesar ciphers is its self-inverse property: because 13 plus 13 equals 26 which equals the alphabet length, encoding and decoding are identical operations. With a Caesar cipher of any other shift such as 3, you need different operations to encode and decode. ROT13 is the only Caesar cipher where one operation does both. This makes it particularly convenient as a simple obfuscation scheme — you do not need to remember whether to use encode or decode mode. The original Caesar cipher uses a shift of 3, which provides no more security than ROT13 but lacks the elegant self-inverse property. Among all possible Caesar cipher shifts, ROT13 is the most commonly known and used because of this convenient property.`,
  },
  {
    q: 'Where is ROT13 commonly used in practice?',
    a: `ROT13 has a long history on the internet as a convention for obfuscating text that you want to make available but not immediately readable. On Usenet, the precursor to internet forums, the convention of encoding joke punchlines, spoilers, and sensitive content in ROT13 dates back to the 1980s. The idea was that casual readers would not see the content accidentally, but anyone who wanted to could decode it with minimal effort, making it a form of voluntary obscuring rather than actual hiding. Reddit uses a similar concept with spoiler tags, but ROT13 remains used in tech communities for punchlines, puzzle answers, and competition spoilers. Some online puzzle competitions and scavenger hunts use ROT13 as one layer of an encoding challenge. Developers sometimes encounter ROT13 in older Unix systems — the rot13 utility has been included in many Unix distributions since the 1980s. ROT13 appears in pop culture references to hacker culture and is often used in educational examples of basic cryptography.`,
  },
  {
    q: 'What happens if I apply ROT13 twice?',
    a: `Applying ROT13 twice always produces the original text, without exception. This is the fundamental mathematical property of ROT13: it is an involution — a function that is its own inverse. This is easy to verify: starting with the letter A, ROT13 gives N. Applying ROT13 to N gives A again because N is the 14th letter, 14 plus 13 equals 27, and 27 mod 26 equals 1, which is A. This works for every letter in the alphabet. For practical purposes, this means you can use the same button or the same tool to both encode and decode ROT13 text. There is no separate decode step needed. This is in contrast to most other ciphers, where encoding and decoding are different operations using different keys or algorithms. If you accidentally apply ROT13 to already-ROT13-encoded text, you recover the original — a useful safety net when working with the cipher manually. In mathematics, ROT13 is an example of a group involution and is often used as an introductory example in discrete mathematics courses.`,
  },
  {
    q: 'How do I implement ROT13 in different programming languages?',
    a: `ROT13 is a common beginner programming exercise. In Python, the built-in codecs module supports ROT13: import codecs and then codecs.encode("Hello", "rot_13") returns "Uryyb". In Python 3, str.maketrans also works by mapping the full alphabet to its rotated version. In JavaScript, you use a regex replace on all letter characters and convert each character code using modular arithmetic. In Unix shell, the command tr A-Za-z N-ZA-Mn-za-m reads from standard input and applies the rotation. In Java, you iterate character by character with modular arithmetic. In Ruby, the tr method maps character ranges directly: "Hello".tr("A-Za-z", "N-ZA-Mn-za-m"). The tr command approach in Ruby and shell is particularly elegant because it directly maps the alphabet to its ROT13 equivalent using character ranges. The modular arithmetic approach in JavaScript and Java is more explicit and easier to understand conceptually.`,
  },
  {
    q: 'What is the history and cultural significance of ROT13?',
    a: `ROT13 occupies a peculiar place in the history of internet culture: it is simultaneously a trivial cipher that any cryptographer would dismiss and a cultural touchstone that represents early internet community norms. Its origin in Usenet reflects a community that valued both open information sharing and voluntary self-censorship of content that might offend or spoil. The convention of ROT13 for spoilers and offensive jokes encoded an implicit social contract: "I am making this available, but I am not forcing it in your face." This is philosophically interesting as a community-designed content moderation mechanism that predated algorithmic content filtering by decades. ROT13 also appears in Eric S. Raymond's "The Jargon File", a compendium of hacker slang, as a defining piece of nerd culture. In modern contexts, ROT13 is often the first cipher taught in introductory cybersecurity courses because it illustrates core concepts — substitution, key or lack thereof, brute-force attacks, and frequency analysis — in a form simple enough to reason about by hand.`,
  },
  {
    q: 'Can ROT13 be useful for any security purpose?',
    a: `ROT13 has no meaningful cryptographic security and should never be used to protect sensitive information. However, it has legitimate uses adjacent to security contexts. In competitive programming and capture-the-flag competitions, ROT13 often appears as one layer of an encoding challenge — participants must recognize and decode it as part of a multi-step puzzle. This makes familiarity with ROT13 useful for security professionals and students. In software development, ROT13 can serve as a do-not-edit signal in generated files or configuration templates — encoding a section in ROT13 signals that the content is machine-generated. For storing mildly sensitive data that you do not want to be immediately readable, ROT13 provides trivial deterrence against casual snooping — it is easily decoded but requires a deliberate step. For any actual security requirement — passwords, personal data, financial data, private communications — use a real cryptographic system such as AES-256 for symmetric encryption or bcrypt for password hashing.`,
  },
  {
    q: 'Does ROT13 work with non-English Latin characters like accented letters?',
    a: `Standard ROT13 only affects the 26 unaccented letters of the basic Latin alphabet in both upper and lowercase. Extended Latin characters with diacritics — such as é, ü, ñ, ç, ø, and ā — are not rotated and pass through unchanged. This is by design in the original specification: ROT13 is defined only for the ASCII letter range. Letters outside this range, including accented characters, digits, spaces, punctuation, and all non-Latin scripts such as Greek, Cyrillic, Arabic, and CJK are left unchanged. This means ROT13 provides no obfuscation for text in languages like French, German, Spanish, Portuguese, or Nordic languages that use common accented characters. For those use cases, a different approach would be needed. In practice, ROT13 is almost exclusively used with English text or ASCII-only strings such as passwords, identifiers, and code, where the limitation to unaccented Latin letters is not a significant constraint.`,
  },
];

export const cipherComparison = [
  { cipher: 'ROT13',    key: 'None (fixed 13)', security: 'None',     use: 'Obfuscation, spoilers'      },
  { cipher: 'Caesar-3', key: 'Shift of 3',       security: 'None',     use: 'Historical curiosity'       },
  { cipher: 'Vigenere', key: 'Keyword string',    security: 'Minimal',  use: 'Historical cipher puzzles'  },
  { cipher: 'AES-128',  key: '128-bit key',       security: 'Strong',   use: 'Real encryption'            },
  { cipher: 'AES-256',  key: '256-bit key',       security: 'Very high',use: 'Sensitive data, TLS'        },
];
