import { FaqItem } from '@/lib/types';

export const faq: FaqItem[] = [
  {
    q: 'What types of whitespace does this tool remove?',
    a: `Whitespace is any character that represents empty space in text. The tool handles four categories: leading and trailing spaces on each line (the spaces you cannot see at the beginning or end of a line), consecutive spaces that collapse multiple spaces down to one, tab characters that jump text across columns, and blank lines that exist purely as empty or whitespace-only rows. Each category is controlled by a separate toggle so you can mix and match operations. For example, you might want to trim line edges and collapse spaces but keep blank lines as paragraph separators. In technical terms, the tool applies a series of JavaScript string replacements in a safe order: tabs first, then multiple spaces, then line trimming, then blank line removal. Applying them in this order prevents a tab being collapsed before it is converted to a space, which would otherwise leave a double space.`,
  },
  {
    q: 'What is the difference between trimming and collapsing whitespace?',
    a: `Trimming removes whitespace from the edges of a line — specifically the leading whitespace before the first non-space character and the trailing whitespace after the last non-space character. For example, "   Hello world   " becomes "Hello world" after trimming. Collapsing replaces multiple consecutive internal spaces with a single space, so "Hello    world" becomes "Hello world". These are different operations and you often need both. A line of text can have both leading spaces from indentation and internal double spaces from sloppy typing or PDF extraction artifacts. Trimming alone would fix the edges but leave internal double spaces. Collapsing alone would fix internal spaces but leave leading or trailing spaces. Using both together produces fully normalized whitespace throughout the text. In programming, this is equivalent to calling trim() plus a regex replace of two-or-more spaces with one, but only within each line rather than globally across the document.`,
  },
  {
    q: 'When should I remove blank lines and when should I keep them?',
    a: `Blank lines serve as visual paragraph separators in plain text, markdown, email, and many other formats. You should keep blank lines when the text is a document with intentional paragraph breaks, when the output will be rendered as HTML where blank lines may not matter but are harmless, when the text is code where blank lines separate logical sections, or when the content is YAML or INI format where blank lines may be meaningful. You should remove blank lines when you are pasting text into a tool that treats every line as a separate record, such as a line-count tool, a duplicate remover, or a database import wizard. You should also remove them when you are normalizing text for comparison — two strings that differ only in blank lines will compare as equal after blank line removal. The tool defaults to keeping blank lines so you do not accidentally lose paragraph structure. Enable blank line removal only when you have a specific need for it.`,
  },
  {
    q: 'Why does text copied from PDFs contain so many extra spaces?',
    a: `PDF files do not store text as a linear stream like a word processor does. Instead, they store text as individual characters or small groups of characters positioned at precise coordinates on a page. When you copy text from a PDF, the copy-paste engine reconstructs a linear text representation by sorting these positioned characters from left to right and top to bottom. Gaps between positioned characters that appear as visual spaces on the page are often reconstructed as multiple space characters rather than a single space, because the copy engine uses position differences to infer spacing. Multi-column PDFs are especially problematic: the reconstruction algorithm may mix columns incorrectly or insert extra line breaks between columns. Scanned PDFs processed with OCR (optical character recognition) often have even worse artifacts because the OCR engine introduces spaces wherever it is unsure about character boundaries. This tool's "collapse spaces" and "trim line edges" options are specifically designed to clean up this type of PDF extraction artifact quickly.`,
  },
  {
    q: 'How does whitespace affect HTML rendering and should I worry about it?',
    a: `HTML browsers collapse whitespace by default according to the CSS white-space property, which defaults to "normal". In this mode, any sequence of whitespace characters within inline content is collapsed to a single space, and leading and trailing whitespace in a block element is ignored. This means extra spaces in your HTML source code are invisible to end users and whitespace cleanup is often unnecessary for the browser to render correctly. However, there are important exceptions. The pre element and elements with white-space: pre or white-space: pre-wrap preserve all whitespace, so extra spaces become visible. Whitespace inside code tags affects how code samples appear. Whitespace in attribute values is significant — extra spaces in a class attribute can cause class matching to fail in older libraries. JavaScript string comparisons are whitespace-sensitive, so values read from form inputs should be trimmed before comparison or storage. Always trim user-supplied values before comparing or saving to a database.`,
  },
  {
    q: 'How does whitespace normalization work in programming?',
    a: `Every major programming language provides string methods for whitespace handling. In JavaScript, String.prototype.trim() removes leading and trailing whitespace. In Python, str.strip() trims edges, and splitting with no argument then rejoining naturally collapses internal whitespace. Java has String.trim() for ASCII whitespace and String.strip() from Java 11 onward for full Unicode whitespace. In SQL, LTRIM and RTRIM are standard for leading and trailing spaces, but internal whitespace normalization requires REGEXP_REPLACE in PostgreSQL or custom logic in SQL Server. Shell scripts use parameter expansion or awk for whitespace normalization. This browser tool is most useful when you are working with text outside of a programming context — copying from email, web pages, PDFs, word processors — and need a fast, visual whitespace cleanup without writing any code. For programmatic normalization integrated into a data pipeline, the language-native approach is more efficient.`,
  },
  {
    q: 'Does whitespace removal affect Unicode or non-Latin text?',
    a: `The tool uses standard JavaScript string methods which are fully Unicode-aware. Trimming removes Unicode whitespace characters including the standard ASCII space, non-breaking space, ideographic space used in CJK typography, em space, en space, and other Unicode whitespace code points. Tab removal converts the standard horizontal tab character. The collapse operation targets consecutive space characters. One nuance: ideographic space used in Japanese and Chinese typography is not replaced by the collapse step because it is not the same code point as the ASCII space. If you have mixed ideographic and ASCII spaces and want all spaces normalized to a single ASCII space, you would need a more specialized tool or a custom regex. For most use cases involving Latin scripts, Arabic, Cyrillic, Hebrew, or standard CJK text, the tool handles whitespace correctly without any extra steps.`,
  },
  {
    q: 'Can I use whitespace removal to normalize text before string comparison?',
    a: `Yes, and this is one of the most valuable uses of whitespace normalization. When comparing user-supplied text with stored values — usernames, email addresses, product names, tags — invisible whitespace differences cause false mismatches. A user who types "  John Smith  " in a form should match a stored record of "John Smith", but a byte-by-byte comparison would fail. Normalizing whitespace before comparison — trimming edges and collapsing internal spaces — makes comparisons whitespace-insensitive. This is standard practice in search engines, form validation, and deduplication pipelines. For manual text comparison, paste both strings into this tool to normalize them, then paste into a text diff tool to isolate any remaining differences. Combined with case normalization, whitespace normalization makes string comparison much more robust. In databases, store values already normalized so that queries, indexes, and uniqueness constraints work correctly without needing to normalize at query time.`,
  },
  {
    q: 'What is the difference between a whitespace remover and a full text cleaner?',
    a: `A whitespace remover is a focused tool that specifically handles space, tab, and line-break characters. A text cleaner is a broader concept that may also remove non-printable control characters such as null bytes or form feeds, strip HTML or Markdown markup, remove diacritics from letters, normalize Unicode form, convert smart quotes to straight quotes, or perform other content-level transformations. This tool is a whitespace remover: it addresses only the four whitespace categories — edge spaces, internal multiple spaces, tabs, and blank lines. It does not strip HTML tags, change letter case, remove punctuation, or alter non-whitespace content. If you also need to strip HTML or clean up encoding artifacts, you would need separate tools for those transformations. This focused scope ensures that whitespace removal is a predictable, reversible operation that does not change the meaning or structure of your text beyond collapsing and trimming spaces.`,
  },
];

export const operationGuide = [
  { label: 'Trim line edges',    desc: 'Removes leading and trailing spaces from every line in the text'         },
  { label: 'Collapse spaces',    desc: 'Replaces 2 or more consecutive spaces with a single space'               },
  { label: 'Convert tabs',       desc: 'Replaces tab characters with a single space character'                   },
  { label: 'Remove blank lines', desc: 'Deletes lines that are empty or contain only whitespace characters'      },
];
